import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

type Language = "ar" | "en";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Sidebar
    'allDocuments': 'كل المستندات',
    'newDocument': 'مستند جديد',
    'documentsLabel': 'المستندات',
    'foldersLabel': 'المساحات العمل',
    'workspaces': 'المساحات العمل',
    'addWorkspace': 'إضافة مساحة عمل',
    'workspaceName': 'اسم مساحة العمل',
    'workspaceType': 'نوع المساحة',
    'enterWorkspaceName': 'أدخل اسم مساحة العمل',
    'workspaceNameRequired': 'اسم مساحة العمل مطلوب',
    'errorCreatingWorkspace': 'فشل إنشاء المساحة',
    'errorUpdatingWorkspace': 'فشل تحديث المساحة',
    'workspaceUpdated': 'تم تحديث مساحة العمل بنجاح',
    'workspaceUpdatePendingWorkflow': 'تم بدء سير العمل. تعديل مساحة العمل في انتظار الموافقة.',
    'editWorkspace': 'تعديل مساحة العمل',
    'save': 'حفظ',
    'saving': 'جاري الحفظ...',
    'workspaceSlug': 'الـ URL Slug',
    'workspaceSlugPlaceholder': 'مثال: my-workspace',
    'workspaceSlugHelp': 'يمكن استخدام أحرف صغيرة وشرطات فقط',
    'workspaceSlugRequired': 'الـ Slug مطلوب',
    'workspacePrivacy': 'الخصوصية',
    'workspaceStorage': 'حد التخزين (MB)',
    'allowInvitesLabel': 'السماح بدعوة أعضاء جدد',
    'private': 'خاص',
    'internal': 'داخلي',
    'public': 'عام',
    'tenantIdNotFound': 'لم يتمكن من العثور على معرف المستأجر. يرجى تسجيل الدخول مرة أخرى.',
    'board': 'مجلس الإدارة',
    'legal': 'قانوني',
    'compliance': 'امتثال',
    'hr': 'الموارد البشرية',
    'projects': 'المشاريع',
    'add': 'إضافة',
    'allFiles': 'كل الملفات',
    'boardMeetings': 'اجتماعات مجلس الإدارة',
    'generalAssembly': 'اجتماعات الجمعيات',
    'committees': 'اجتماعات اللجان',
    'resolutions': 'القرارات',
    'quickAccess': 'الوصول السريع',
    'file': 'ملف',
    'folder': 'مجلد',
    'folders': 'المجلدات',
    'totalDocuments': 'إجمالي المستندات',
    'totalWorkspaces': 'إجمالي مساحات العمل',
    'unsentDocuments': 'المستندات غير المرسلة',
    'subject': 'الموضوع',
    'updated': 'محدث',
    'progress': 'التقدم',
    'signingWorkflow': 'سير عمل التوقيع',
    'noRecipientsYet': 'لا يوجد مستلمون مضافون بعد',
    'viewDocument': 'عرض المستند',
    'filters': 'التصفيات',
    'searchDocuments': 'البحث في المستندات...',
    'editFields': 'تعديل الحقول',
    'documentPreview': 'معاينة المستند',
    'openInNewTab': 'فتح في علامة تبويب جديدة',
    'errorSaving': 'فشل في الحفظ',
    'resend': 'إعادة إرسال',
    'pendingTasks': 'المهام المعلقة',
    'upcomingObligations': 'الالتزامات القادمة',
    'pendingAgentActions': 'إجراءات الوكيل المعلقة',
    'recentActivity': 'النشاط الأخير',
    'dashboard': 'لوحة القيادة',
    'welcomeBack': 'مرحباً بعودتك ،',
    'dashboardGreetingDesc': 'إليك ما يحدث في مستنداتك اليوم.',
    'dashboardSubtitle': 'نظرة عامة على خزانتك ورؤى',
    'aiSearchPlaceholder': "اسأل الذكاء الاصطناعي: 'عرض المستندات المعلقة' أو 'ابحث عن العقود من الأسبوع الماضي'...",
    'latestUpdates': 'آخر التحديثات على مستنداتك',
    'documentCreated': 'تم إنشاء المستند',
    'getStartedTasks': 'ابدأ بالمهام الشائعة',
    'uploadAndSend': 'رفع وإرسال للتوقيع',
    'useTemplate': 'استخدام قالب',
    'startFromTemplate': 'البدء من قالب',
    'teamSettings': 'إعدادات الفريق',
    'manageTeamMembers': 'إدارة أعضاء الفريق',
    'readyToSend': 'جاهز للإرسال؟',
    'createAndSign': 'أنشئ مستنداً جديداً واحصل على توقيعه في دقائق.',
    'daysAgo': 'أيام مضت',
    'viewAll': 'عرض الكل',
    'seeMore': 'عرض المزيد',
    'seeLess': 'عرض أقل',
    'noRecentActivity': 'لم يتم العثور على نشاط أخير.',
    'quickActions': 'إجراءات سريعة',
    'createTask': 'إنشاء مهمة',
    'startWorkflow': 'بدء سير عمل',
    'noUpcomingObligations': 'لا توجد التزامات قادمة',
    'items': 'عناصر',
    'viewDetails': 'عرض التفاصيل',
    'noPendingActions': 'لا توجد إجراءات معلقة',
    'needsApproval': 'يحتاج إلى موافقة',
    'reviewActions': 'مراجعة الإجراءات',
    'addFolder': 'إضافة مجلد',
    'folderName': 'اسم المجلد',
    'enterFolderName': 'أدخل اسم المجلد',
    'select': 'اختر',
    'folderNameRequired': 'اسم المجلد مطلوب',
    'isStarred': 'مميز بنجمة',
    'removeFromStarred': 'إزالة من المميزة بنجمة',
    'addToStarred': 'إضافة إلى المميزة بنجمة',
    'addToFavorites': 'إضافة إلى المفضلة',
    'removeFromFavorites': 'إزالة من المفضلة',
    'addedToFavorites': 'تم الإضافة إلى المفضلة',
    'removedFromFavorites': 'تم الإزالة من المفضلة',
    'errorUpdatingFavorites': 'خطأ في تحديث المفضلة',
    'noStarredItems': 'لا توجد عناصر مميزة بنجمة بعد',
    'noItemsFound': 'لم يتم العثور على عناصر',
    'noDocumentsFound': 'لم يتم العثور على مستندات',
    'sharedWithMe': 'مشارك معي',
    'searchVault': 'بحث في الخزنة',
    'tasks': 'المهام',
    'activities': 'الأنشطة',
    'obligations': 'الالتزامات',
    'workflowInstances': 'مثيلات سير العمل',
    'retentionPolicies': 'سياسات الاحتفاظ',
    'extractionReview': 'مراجعة الاستخراج',
    'invitations': 'الدعوات',
    'agentActions': 'إجراءات الوكيل',
    'auditLogs': 'سجلات التدقيق',
    'adminSettings': 'إعدادات المسؤول',
    'noWorkspacesYet': 'لا توجد مساحات عمل بعد',
    'noWorkspacesDesc': 'أنشئ مساحة عملك الأولى للبدء في تنظيم مستنداتك.',
    'newWorkspace': 'مساحة عمل جديدة',
    'createWorkspaceDesc': 'أنشئ مساحة عمل جديدة لتنظيم مستنداتك.',

    // Menu Actions
    'openMenu': 'فتح القائمة',
    'moreActions': 'المزيد من الإجراءات',
    'share': 'مشاركة',
    'duplicate': 'تكرار',
    'delete': 'حذف',
    'download': 'تحميل',
    'rename': 'إعادة تسمية',
    'copy': 'نسخ',
    'cut': 'قص',
    'paste': 'لصق',
    'starred': 'مميز بنجمة',

    // Accessibility
    'breadcrumb': 'مسار التنقل',
    'starredSubtitle': 'جميع الملفات التي قمت بتمييزها بنجمة',
    'noStarredDocuments': 'لا توجد ملفات مميزة بنجمة',
    'noStarredDocumentsDesc': 'قم بتمييز الملفات المهمة بنجمة للوصول إليها بسهولة من هنا',
    'sharedSubtitle': 'الملفات التي شاركها الآخرون معك',
    'noSharedDocuments': 'لا توجد ملفات مشاركة',
    'noSharedDocumentsDesc': 'الملفات التي تتم مشاركتها معك ستظهر هنا',

    // Workspace Features
    'workspace': 'مساحة العمل',
    'members': 'الأعضاء',
    'workspaceMembers': 'أعضاء مساحة العمل',
    'inviteMembers': 'دعوة أعضاء',
    'member': 'عضو',
    'joinedDate': 'تاريخ الانضمام',
    'removeMember': 'إزالة عضو',
    'confirmRemoveMember': 'هل أنت متأكد من إزالة هذا العضو؟',
    'inviteToWorkspace': 'دعوة لمساحة العمل',
    'inviteDesc': 'إرسال دعوة للانضمام إلى مساحة العمل هذه.',
    'inviteMembersDescription': 'قم بدعوة المستخدمين للتعاون في مساحة العمل هذه.',
    'emailAddress': 'البريد الإلكتروني',
    'admin': 'مسؤول',
    'guest': 'ضيف',
    'optional': 'اختياري',
    'sendInvite': 'إرسال دعوة',
    'inviteSentSuccess': 'تم إرسال الدعوة بنجاح!',
    'settings': 'الإعدادات',
    'workspaceSettings': 'إعدادات مساحة العمل',
    'generalSettings': 'الإعدادات العامة',
    'saveChanges': 'حفظ التغييرات',
    'current': 'الحالية',
    'dangerZone': 'منطقة الخطر',
    'confirmDeleteWorkspace': 'هل أنت متأكد من أنك تريد حذف مساحة العمل هذه وكل محتوياتها؟',
    'workspaceDeleted': 'تم حذف مساحة العمل بنجاح.',
    'errorDeletingWorkspace': 'فشل حذف مساحة العمل',
    'deleteWorkspace': 'حذف مساحة العمل',
    'deleteFolder': 'حذف المجلد',
    'confirmDeleteFolder': 'هل أنت متأكد من أنك تريد حذف هذا المجلد وكل محتوياته؟',
    'folderDeleted': 'تم حذف المجلد بنجاح',
    'errorDeletingFolder': 'فشل حذف المجلد',
    'confirmDeleteDocument': 'هل أنت متأكد من أنك تريد حذف هذا المستند؟',
    'documentDeleted': 'تم حذف المستند بنجاح',
    'errorDeletingDocument': 'فشل حذف المستند',
    'recycleBin': 'سلة المحذوفات',
    'errorLoadingWorkspace': 'خطأ في تحميل مساحة العمل',
    'restore': 'استعادة',
    'Msg_RestoredSuccessfully': 'تمت الاستعادة بنجاح',
    'resendSuccess': 'تم إعادة إرسال سير العمل بنجاح',




    'actions': 'الإجراءات',
    'type': 'النوع',
    'deletedBy': 'حُذف بواسطة',
    'deletedAt': 'حُذف في',
    'document': 'مستند',
    'sortBy': 'ترتيب حسب',
    'name': 'الاسم',
    'pendingActions': 'إجراءات معلقة',
    'documentsRequireAttention': 'مستندات تتطلب انتباهك',
    'suggested': 'مقترحة',
    'recentDocuments': 'المستندات الأخيرة',
    'all': 'الكل',
    'pendingSignature': 'في انتظار التوقيع',
    'inReview': 'قيد المراجعة',
    'approved': 'معتمد',
    'signed': 'موقع',
    'searchInVault': 'ابحث في Vault',
    'advancedSearch': 'بحث متقدم',
    'askVault': 'اسأل Vault',
    'goToGRC': 'اذهب إلى GRC',
    'menu': 'القائمة',
    'changePassword': 'تغيير كلمة المرور',
    'logout': 'خروج',
    'home': 'الرئيسية',
    'requiredField': 'حقل مطلوب',
    'license': 'رخصة',
    'partnershipAgreement': 'اتفاقية شراكة استراتيجية',
    'agreement': 'اتفاقية',
    'annualReport': 'التقرير السنوي 2024',
    'report': 'تقرير',
    'dataProcessing': 'اتفاقية معالجة البيانات',
    'consultingContract': 'عقد استشاري - الربع الأول 2025',
    'antiMoneyLaundering': 'سياسة مكافحة غسل الأموال',
    'shareholderAgreement': 'اتفاقية المساهمين',

    // Status
    'expired': 'منتهي الصلاحية',
    'draft': 'مسودة',

    // Dates
    'today': 'اليوم',
    'yesterday': 'أمس',
    'dec26': '26 ديسمبر',
    'dec18': '18 ديسمبر',

    // Registration
    'createAccount': 'إنشاء حساب جديد',
    'signUpMessage': 'أنشئ حسابك للوصول إلى جميع المميزات',
    'fullName': 'الاسم الكامل',
    'enterFullName': 'أدخل اسمك الكامل',
    'fullNameAr': 'الاسم الكامل (عربي)',
    'enterFullNameAr': 'أدخل الاسم الكامل بالعربية',
    'fullNameEn': 'الاسم الكامل (إنجليزي)',
    'enterFullNameEn': 'أدخل الاسم الكامل بالإنجليزية',
    'companyName': 'اسم الشركة',
    'enterCompanyName': 'أدخل اسم الشركة',
    'companyNameAr': 'اسم الشركة (عربي)',
    'enterCompanyNameAr': 'أدخل اسم الشركة بالعربية',
    'companyNameEn': 'اسم الشركة (إنجليزي)',
    'enterCompanyNameEn': 'أدخل اسم الشركة بالإنجليزية',
    'email': 'البريد الإلكتروني',
    'enterEmail': 'أدخل بريدك الإلكتروني',
    'password': 'كلمة المرور',
    'enterPassword': 'أدخل كلمة المرور',
    'confirmPassword': 'تأكيد كلمة المرور',
    'enterConfirmPassword': 'أعد إدخال كلمة المرور',
    'register': 'تسجيل',
    'registering': 'جاري التسجيل...',
    'alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'login': 'تسجيل الدخول',

    // Validation
    'nameRequired': 'الاسم مطلوب',
    'nameMinLength': 'الاسم يجب أن يكون حرفين على الأقل',
    'fullNameArRequired': 'الاسم الكامل بالعربية مطلوب',
    'fullNameEnRequired': 'الاسم الكامل بالإنجليزية مطلوب',
    'companyNameArRequired': 'اسم الشركة بالعربية مطلوب',
    'companyNameEnRequired': 'اسم الشركة بالإنجليزية مطلوب',
    'emailRequired': 'البريد الإلكتروني مطلوب',
    'emailInvalid': 'البريد الإلكتروني غير صحيح',
    'passwordRequired': 'كلمة المرور مطلوبة',
    'passwordMinLength': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
    'passwordLowercase': 'كلمة المرور يجب أن تحتوي على حرف صغير',
    'passwordUppercase': 'كلمة المرور يجب أن تحتوي على حرف كبير',
    'passwordNumber': 'كلمة المرور يجب أن تحتوي على رقم',
    'passwordSpecialChar': 'كلمة المرور يجب أن تحتوي على رمز خاص',
    'confirmPasswordRequired': 'تأكيد كلمة المرور مطلوب',
    'passwordsNotMatch': 'كلمات المرور غير متطابقة',
    'weak': 'ضعيفة',
    'medium': 'متوسطة',
    'strong': 'قوية',
    'registrationSuccess': 'تم التسجيل بنجاح!',
    'registrationError': 'حدث خطأ أثناء التسجيل',
    'upload': 'رفع',
    'title': 'العنوان',
    'enterTitle': 'أدخل عنوان المستند',
    'clickToUpload': 'اضغط لاختيار ملف',
    'uploading': 'جاري الرفع...',
    'documentTitle': 'عنوان المستند',
    'selectWorkspace': 'اختر مساحة العمل',
    'fillAllFields': 'يرجى ملء جميع الحقول',
    'errorLoadingWorkspaces': 'فشل في تحميل مساحات العمل',
    'selectDocumentType': 'اختر نوع المستند',
    'uploadError': 'فشل رفع المستند. يرجى المحاولة مرة أخرى.',
    'updateDocument': 'تحديث المستند',
    'updateError': 'فشل تحديث المستند. يرجى المحاولة مرة أخرى.',
    'update': 'تحديث',
    'updating': 'جاري التحديث...',
    'lowConfidence': 'ثقة منخفضة',
    'mediumConfidence': 'ثقة متوسطة',
    'highConfidence': 'ثقة عالية',
    'reviewDocumentClassification': 'مراجعة تصنيف المستند',
    'reviewRequiredMessage': 'يتطلب هذا التصنيف مراجعتك وتأكيدك.',
    'highConfidenceMessage': 'الذكاء الاصطناعي واثق من هذا التصنيف، ولكن يرجى التحقق.',
    'confidence': 'الثقة',
    'extractedFields': 'الحقول المستخرجة',
    'reviewFieldsMessage': 'مراجعة وتصحيح المعلومات المستخرجة أدناه:',
    'enterValue': 'أدخل قيمة',
    'lowConfidenceWarning': 'ثقة منخفضة',
    'lowConfidenceWarningMessage': 'الذكاء الاصطناعي لديه ثقة منخفضة في هذا التصنيف. يرجى مراجعة كافة الحقول بعناية قبل الموافقة.',
    'reject': 'رفض',
    'approveAndSave': 'موافقة وحفظ',
    'previewFailed': 'فشل المعاينة',
    'preview': 'معاينة',
    'confirmDelete': 'هل أنت متأكد أنك تريد حذف هذا المستند؟',
    'deleteSuccess': 'تم حذف المستند بنجاح',
    'deleteFailed': 'فشل حذف المستند',

    // Login
    'loginTitle': 'تسجيل الدخول',
    'loginMessage': 'تسجيل الدخول للوصول إلى حسابك',
    'forgotPassword': 'هل نسيت كلمة المرور؟',
    'rememberMe': 'تذكرني',
    'loginBtn': 'تسجيل الدخول',
    'loggingIn': 'جاري تسجيل الدخول...',
    'noAccount': 'لا تملك حساب؟',
    'signUp': 'إنشاء حساب جديد',
    'passwordMinLoginLength': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'loginSuccess': 'تم تسجيل الدخول بنجاح!',
    'companyChangedSuccess': 'تم تغيير الشركة بنجاح',
    'selectCompany': 'اختر الشركة',
    'selectCompanySubtitle': 'يرجى اختيار إحدى شركاتك للمتابعة',
    'searchCompanyPlaceholder': 'البحث عن شركة...',
    'adminEmail': 'البريد الإلكتروني للأدمن',
    'adminPassword': 'كلمة مرور الأدمن',
    'companyRequired': 'اختيار الشركة اجباري',
    'loginError': 'حدث خطأ أثناء تسجيل الدخول',
    'invalidCredentials': 'البريد الإلكتروني أو كلمة المرور غير صحيح',
    'partnerTab': 'شريك ',
    'employeeTab': 'موظف',
    'adminPartnerLoginTitle': 'دخول أدمن كشريك',
    'enterIdentityNumber': 'أدخل رقم الهوية',
    'identityNumberRequired': 'رقم الهوية مطلوب',
    'otpSentSuccess': 'تم إرسال رمز التحقق بنجاح',
    'otpSentToPhones': 'تم إرسال رمز التحقق إلى الأرقام التالية:',
    'seconds': 'ثانية',
    // Forgot Password
    'forgotPasswordTitle': 'هل نسيت كلمة المرور؟',
    'forgotPasswordMessage': 'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور',
    'sendResetLink': 'إرسال رابط إعادة التعيين',
    'resetLinkSent': 'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني',
    'sending': 'جاري الإرسال...',
    'verifyEmailTitle': 'تحقق من بريدك الإلكتروني',
    'verifyEmailMessage': 'لقد أرسلنا رمز التحقق إلى',
    'verificationCode': 'رمز التحقق',
    'enterVerificationCode': 'أدخل رمز من 5 أرقام',
    'verificationHint': 'تحقق من بريدك الإلكتروني للحصول على الرمز',
    'verify': 'التحقق',
    'verifyingCode': 'جاري التحقق من الرمز...',
    'resendCode': 'إعادة إرسال الرمز',
    'resendCodeSent': 'تم إرسال الرمز إلى بريدك الإلكتروني!',
    'resendOtp': 'إعادة إرسال الرمز',
    'resendOtpIn': 'إعادة إرسال الرمز خلال',
    'resetPasswordTitle': 'إعادة تعيين كلمة المرور',
    'resetPasswordMessage': 'أدخل كلمة المرور الجديدة أدناه',
    'newPassword': 'كلمة المرور الجديدة',
    'resetPassword': 'إعادة تعيين كلمة المرور',
    'resettingPassword': 'جاري إعادة تعيين كلمة المرور...',
    'passwordResetSuccess': 'تم إعادة تعيين كلمة المرور بنجاح!',
    'passwordResetError': 'حدث خطأ أثناء إعادة تعيين كلمة المرور',
    'passwordValidationError': 'يرجى التحقق من متطلبات كلمة المرور',
    'invalidVerificationCode': 'رمز التحقق غير صحيح',
    'verificationCodeRequired': 'يرجى إدخال رمز التحقق',
    'error': 'حدث خطأ',
    'mustBeArabic': 'يجب أن يكون باللغة العربية',
    'mustBeEnglish': 'يجب أن يكون باللغة الإنجليزية',

    // Invitation Accept
    'verifyInvitation': 'تحقق من دعوتك',
    'otpSentTo': 'لقد أرسلنا رمز تحقق مكون من 6 أرقام إلى',
    'enterOtpCode': 'أدخل الرمز',
    'verifyCode': 'تحقق من الرمز',
    'verifyingOtp': 'جاري التحقق...',
    'didntReceiveCode': 'لم تستلم الرمز؟',
    'resendOtpCode': 'إعادة إرسال الرمز',
    'invalidOtp': 'رمز OTP غير صالح. يرجى المحاولة مرة أخرى.',
    'enterAllDigits': 'الرجاء إدخال جميع الأرقام الـ 6',
    'invitationAccepted': 'تم قبول الدعوة بنجاح!',
    'invalidInvitationLink': 'رابط دعوة غير صالح',
    'otpGenerationFailed': 'فشل في إنشاء رمز OTP',
    'goToLogin': 'الذهاب إلى تسجيل الدخول',
    'previewNotAvailable': 'لا تتوفر معاينة لهذا النوع من الملفات',
    'downloadToView': 'تحميل للعرض',
    'fileReady': 'مستندك جاهز للتحميل',
    'backToLogin': 'العودة إلى تسجيل الدخول',

    // Profile
    'profile': 'الملف الشخصي',
    'profileSubtitle': 'إدارة معلومات حسابك الشخصية',
    'edit': 'تعديل',
    // 'save': 'حفظ',

    'personalInfo': 'المعلومات الشخصية',
    'firstName': 'الاسم الأول',
    'lastName': 'الاسم الأخير',
    'phone': 'رقم الهاتف',
    'bio': 'السيرة الذاتية',
    'address': 'العنوان',
    'city': 'المدينة',
    'country': 'الدولة',
    'workInfo': 'معلومات العمل',
    'company': 'الشركة',
    'position': 'المنصب',
    'joinedOn': 'انضم في',
    'registeredUser': 'مستخدم مسجل',
    'businessAccount': 'حساب أعمال',
    'organizationInfo': 'معلومات المنظمة',
    'accountType': 'نوع الحساب',

    // Change Password
    'currentPassword': 'كلمة المرور الحالية',
    'enterCurrentPassword': 'أدخل كلمة المرور الحالية',

    'enterNewPassword': 'أدخل كلمة المرور الجديدة',
    'confirmNewPassword': 'أعد إدخال كلمة المرور الجديدة',
    'updatePassword': 'تحديث كلمة المرور',
    'changingPassword': 'جاري التغيير...',
    'changePasswordMessage': 'تحديث كلمة المرور الخاصة بك',
    'passwordChangeSuccess': 'تم تغيير كلمة المرور بنجاح!',
    'passwordChangeError': 'حدث خطأ أثناء تغيير كلمة المرور',
    'passwordSameAsOld': 'كلمة المرور الجديدة يجب أن تكون مختلفة عن القديمة',
    'passwordsMatch': 'كلمات المرور متطابقة',
    'fixErrors': 'يرجى تصحيح الأخطاء في النموذج',
    'passwordStrength': 'قوة كلمة المرور',
    'backToHome': 'العودة للصفحة الرئيسية',

    // AI Chat
    'aiChatGreeting': 'كيف يمكنني مساعدتك اليوم؟',
    'whatToStartWith': 'بماذا تريد أن تبدأ؟',
    'message': 'رسالة',
    'uploadFile': 'رفع ملف',
    'draftMode': 'وضع المسودة',
    'autoMode': 'الوضع التلقائي',
    'agentUsingPrefix': 'أنا أستخدم',
    'agentModePrefix': 'في وضع',
    'draftModeDesc': 'في وضع المسودة، سأقترح الإجراءات للمراجعة والموافقة قبل التنفيذ.',
    'autoModeDesc': 'في وضع تلقائي، سأنفذ الإجراءات تلقائيًا ضمن قواعد السلامة المحددة.',
    'agentFileUploaded': 'لقد رأيت أنك قمت برفع',
    'agentMessageReceived': 'استلمت رسالتك: ',
    'agentSimulatedResponse': 'هذا رد محاكاة.',
    'selectAgent': 'اختر الوكيل',
    'removeAttachment': 'إزالة المرفق',

    // Agents
    'agent_auto': 'المساعد الذكي (تلقائي)',
    'agent_docs': 'وكيل المستندات',
    'agent_deadlines': 'المواعيد النهائية والانتهاء',
    'agent_signing': 'وكيل التوقيع',
    'agent_governance': 'وكيل الحوكمة',
    'agent_audit': 'التدقيق والامتثال',
    'agent_access': 'الوصول والأذونات',
    'agent_insights': 'الرؤى والملخص',

    // Agent Descriptions
    'agent_desc_auto': 'الأفضل للاستفسارات العامة',
    'agent_desc_docs': 'استعلم عن ملفاتك وعقودك',
    'agent_desc_deadlines': 'تتبع المواعيد الهامة',
    'agent_desc_signing': 'حالة التوقيع وسير العمل',
    'agent_desc_governance': 'قواعد الحوكمة والامتثال',
    'agent_desc_audit': 'سجلات التدقيق والفحوصات',
    'agent_desc_access': 'أدوار المستخدمين والصلاحيات',
    'agent_desc_insights': 'تحليل البيانات والملخصات',

    // Suggestions
    'suggestion_expiring': 'المستندات المنتهية',
    'suggestion_expiring_desc': 'اعرض المستندات المنتهية هذا الأسبوع',
    'suggestion_summarize': 'تلخيص اجتماع',
    'suggestion_summarize_desc': 'لخص محضر اجتماع مجلس الإدارة الأخير',
    'suggestion_access': 'فحص الوصول',
    'suggestion_access_desc': 'من لديه حق الوصول لمجلد HR؟',
    'suggestion_draft': 'صياغة عقد',
    'suggestion_draft_desc': 'صغ مسودة اتفاقية عدم إفصاح',

    // Common
    'gridView': 'عرض الشبكة',
    'listView': 'عرض القائمة',
    'back': 'عودة',
    'details': 'التفاصيل',
    'yes': 'نعم',
    'no': 'لا',
    'documentNotFound': 'المستند غير موجود',

    // Document Fields
    'id': 'الرقم التعريفي',
    'category': 'الفئة',
    'status': 'الحالة',
    'date': 'التاريخ',
    'size': 'الحجم',
    'owner': 'المالك',
    'general': 'عام',
    'documentFetchError': 'فشل في تحميل تفاصيل المستند',
    'kb': 'كيلوبايت',
    'noDocuments': 'لا توجد مستندات',
    'noDocumentsDescription': 'لا توجد مستندات في مساحة العمل هذه بعد. يمكنك البدء برفع مستند جديد.',
    'noVersionsDescription': 'لا يوجد نسخ سابقة لهذا المستند.',

    // Share Modal
    'shareDocument': 'مشاركة المستند',
    'shareDescription': 'شارك هذا الرابط مع الآخرين لعرض',
    'copyLink': 'نسخ الرابط',
    'linkCopied': 'تم النسخ!',
    'close': 'إغلاق',
    'expiryDateKeywords': 'تاريخ الانتهاء مطلوب',
    'invalidEmail': 'البريد الإلكتروني غير صحيح',
    'confirmDeleteInvitation': 'هل أنت متأكد من إزالة الوصول لهذا المستخدم؟',
    'invitationDeleted': 'تم إزالة الوصول بنجاح',
    'deleteInvitationFailed': 'فشل إزالة الوصول',
    'fetchInvitationsFailed': 'فشل جلب الدعوات',
    'shareSuccess': 'تم مشاركة المستند بنجاح',
    'shareFailed': 'فشل مشاركة المستند',
    'peopleWithAccess': 'أشخاص لديهم وصول',
    'sharing': 'جاري المشاركة...',
    'expiryDate': 'تاريخ الانتهاء',

    // Document Upload
    'uploadDocument': 'رفع مستند',
    'uploadNewDocument': 'رفع مستند جديد',
    'dragDropFile': 'اسحب وأفلت الملف هنا',
    'orClickToBrowse': 'أو انقر للاستعراض',
    'documentName': 'اسم المستند',
    'enterDocumentName': 'أدخل اسم المستند',
    'selectCategory': 'اختر الفئة',
    'financial': 'مالي',
    'technical': 'تقني',
    'description': 'الوصف',
    'enterDescription': 'أدخل الوصف',


    'documentType': 'نوع المستند',
    'workflows': 'سير العمل',
    'noActiveWorkflows': 'لا توجد سير عمل نشطة',
    'by': 'بواسطة',
    'assignedTo': 'مسند إلى',
    'tags': 'العلامات',
    'enterTags': 'أدخل العلامات (مثل: عاجل، سري)',
    'Draft': 'مسودة',
    'InReview': 'قيد المراجعة',
    'Approved': 'معتمد',
    'Signed': 'موقع',
    'Pending': 'قيد الانتظار',
    'Rejected': 'مرفوض',
    'Executed': 'منفذ',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'created': 'تم الإنشاء',





    // ===== Workspace Invite & Permissions =====
    manageWorkspaceMembers: 'إدارة أعضاء مساحة العمل',
    manageWorkspaceMembersDesc: 'يمكنك تغيير دور كل مستخدم من القائمة أدناه:',
    adding: 'جاري الإضافة...',
    role: 'الدور',
    managePermissions: 'إدارة الأذونات',
    inviteUser: 'دعوة مستخدم',
    userAlreadyHasAccess: 'المستخدم لديه وصول بالفعل',
    confirmRemoveUser: 'هل أنت متأكد من أنك تريد إزالة هذا المستخدم؟',
    searchUsers: 'البحث عن مستخدمين...',
    noUsersFound: 'لم يتم العثور على مستخدمين',
    invite: 'دعوة',
    cancel: 'إلغاء',
    you: 'أنت',
    failedToLoadMembers: 'فشل تحميل الأعضاء',
    memberRemovedSuccessfully: 'تم إزالة العضو بنجاح',
    failedToRemoveMember: 'فشل إزالة العضو',
    roleUpdatedSuccessfully: 'تم تحديث الدور بنجاح',
    failedToUpdateRole: 'فشل تحديث الدور',
    failedToLoadData: 'فشل تحميل البيانات',
    invitationSentSuccessfully: 'تم إرسال الدعوة بنجاح',
    failedToInviteUser: 'فشل إرسال الدعوة',
    noMembersFound: 'لم يتم العثور على أعضاء',
    noMembersFoundDescription: 'قم بدعوة مستخدمين للتعاون في مساحة العمل هذه.',
    Admin: 'مسؤول',
    Editor: 'محرر',
    Viewer: 'مشاهد',

    // ===== Document Details =====
    legalHold: 'الحجز القانوني',
    legalHoldActive: 'هذه المساحة تحت الحجز القانوني',
    legalHoldBannerTitle: '⚠️ الحجز القانوني مفعّل',
    legalHoldBannerDesc: 'هذه المساحة خاضعة للحجز القانوني — لا يمكن التعديل أو الحذف حتى يتم رفع الحجز.',
    legalHoldLockedEdit: 'التعديل مقفول بسبب الحجز القانوني',
    legalHoldLockedDelete: 'الحذف مقفول بسبب الحجز القانوني',
    legalHoldLockedMsg: 'لا يمكن تعديل أو حذف مجلدات النظام، أو تعيين مسارات عمل لها.',
    workspaceDeletePendingWorkflow: 'تم إرسال طلب الحذف — يحتاج موافقة من المهام',
    documentDeletePendingWorkflow: 'تم إرسال طلب حذف المستند — في انتظار موافقة مسار العمل',
    statusAndCompliance: 'الحالة والامتثال',
    generalInfo: 'معلومات عامة',
    activeHold: 'نشط',
    createdDate: 'تاريخ الإنشاء',
    noDescription: 'لا يوجد وصف لهذا المستند.',
    versionHistory: 'سجل النسخ',
    permissions: 'الأذونات',
    documentDetails: 'تفاصيل المستند',
    downloadDocument: 'تحميل المستند',
    noOneHasAccess: 'لا يوجد أشخاص لديهم وصول',
    noVersions: 'لا توجد نسخ سابقة',
    removeAccess: 'إزالة الوصول',

    // ===== Document Versions =====
    uploadNewVersion: 'رفع نسخة جديدة',
    latest: 'الأحدث',
    confirmDeleteVersion: 'هل أنت متأكد من حذف هذه النسخة؟',
    versionDeleted: 'تم حذف النسخة بنجاح',
    deleteError: 'فشل حذف النسخة',
    versionsLoadError: 'فشل تحميل نسخ المستند',
    versionUploaded: 'تم رفع النسخة الجديدة بنجاح',

    // ===== Common =====
    search: "بحث",

    // ===== Workflows =====
    workflowsTitle: "سير العمل",
    requestedBy: "بواسطة",
    relatedItem: "العنصر المرتبط",
    WorkflowInstance: "سير عمل",
    deactivateWorkflow: "تعطيل سير العمل",
    deactivateToEdit: "عطّل سير العمل أولاً للتعديل",
    cannotEditActiveWorkflow: "لا يمكن تعديل سير عمل نشط — يرجى تعطيله أولاً",
    onlyOneStartNodeAllowed: "مسموح بنقطة بداية واحدة فقط لكل سير عمل",
    onlyOneEndNodeAllowed: "مسموح بنقطة نهاية واحدة فقط لكل سير عمل",
    workflowSaved: "تم حفظ سير العمل بنجاح",
    failedToSaveWorkflow: "فشل حفظ سير العمل",
    confirmDeactivateWfWithInstances: "هناك نماذج نشطة مرتبطة بسير العمل هذا. سيؤدي التعطيل إلى إنهائها جميعًا وتعطيل التعيينات. هل أنت متأكد؟",
    activateWorkflow: "تفعيل سير العمل",
    confirmActivateWf: "هل أنت متأكد من تفعيل سير العمل هذا؟",
    activateAssignmentsWithWorkflow: "تفعيل التعيينات المرتبطة بسير العمل أيضاً",
    viewAssignments: "تكوين تعيينات سير العمل",
    viewActiveInstances: "عرض النماذج النشطة",
    deactivate: "تعطيل",
    activate: "تفعيل",
    failedToToggleWorkflow: "فشل تغيير حالة سير العمل",
    workflowInstancesTitle: "مثيلات سير العمل",
    workflowActivated: "تم تفعيل سير العمل بنجاح",
    workflowDeactivated: "تم تعطيل سير العمل بنجاح",
    workflowInstancesSubtitle: "تتبع عمليات سير العمل النشطة والمكتملة",
    newWorkflow: "سير عمل جديد",
    workflowNamePlaceholder: "اسم سير العمل",
    workflowDescriptionPlaceholder: "الوصف",
    draftStatus: "مسودة",
    activeStatus: "نشط",
    archivedStatus: "مؤرشف",
    steps: "الخطوات",
    assignedWorkspaces: "مساحات العمل المخصصة",
    activeInstances: "العمليات الجارية",
    completedInstances: "العمليات المكتملة",
    assignedDocuments: "المستندات المخصصة",
    Running: "جارية",
    Completed: "مكتملة",
    Docs: "مستندات",
    Folders: "مجلدات",
    Workspaces: "مساحات العمل",
    triggers: "المشغلات",
    addStep: "إضافة خطوة",
    addTrigger: "إضافة مشغل",
    addTriggerGroup: "إضافة مجموعة مشغلات",
    editTriggerGroup: "تعديل مجموعة مشغلات",
    triggerType: "نوع المشغل",
    triggerValue: "القيمة / المعرف",
    fileFormatTrigger: "تنسيق الملف (الامتداد)",
    personTrigger: "شخص (معرف المستخدم)",
    workspaceTrigger: "مساحة العمل (معرف المساحة)",
    folderEventTrigger: "مجلد/علامة",
    stepTitle: "عنوان الخطوة",
    actionType: "نوع الإجراء",
    instructions: "التعليمات",
    requiredFields: "الحقول المطلوبة (مفصولة بفواصل)",
    waitForDeps: "ينتظر (التبعيّات)",
    done: "تم",
    approveAction: "موافقة/رفض",
    fillAction: "تعبئة بيانات",
    reviewAction: "مراجعة",
    runningStatus: "جاري التشغيل",
    failedStatus: "فشل",
    completedStatus: "مكتمل",
    pausedStatus: "متوقف مؤقتًا",
    terminatedStatus: "منتهي",
    suspendedStatus: "معلق",
    pendingStatus: "قيد الانتظار",
    createdBy: "أنشأ بواسطة",
    contextData: "تفاصيل السياق",
    currentStep: "الخطوة الحالية",
    startedAt: "بدأ في",
    completedAt: "اكتمل في",
    confirmDeleteWorkflow: 'حذف سير العمل',
    confirmDeleteWorkflowDescription: 'هل أنت متأكد من حذف سير العمل هذا؟ لا يمكن التراجع عن هذا الإجراء.',
    workflowDeletedSuccessfully: 'تم حذف سير العمل بنجاح',
    failedToDeleteWorkflow: 'فشل حذف سير العمل',
    failedToLoadWorkflows: 'فشل تحميل سير العمل',
    failedToLoadWorkflow: 'فشل تحميل بيانات سير العمل',

    selectTrigger: "اختر المشغل",
    // Workflow Editor
    event: "الحدث",
    selectEvent: "اختر الحدث",
    fieldsConfigured: "حقول تم تكوينها",
    workflowSettings: "إعدادات سير العمل",
    edgeProperties: "خصائص الرابط",
    deleteConnection: "حذف الرابط",
    connectionName: "اسم الرابط",
    before: "قبل",
    during: "أثناء",
    after: "بعد",
    transitionForms: "نماذج الانتقال",
    configureForms: "تكوين النماذج",
    scopeTriggers: "المشغلات",
    flowShapes: "أشكال التدفق",
    instructionsTitle: "تعليمات",
    dragShapesInstruction: "اسحب الأشكال إلى اللوحة. قم بتوصيلها لتحديد التدفق. حدد عقدة لتكوين الخصائص على اليمين.",
    noScopesDefined: "لم يتم تعريف نطاقات. الاستخدام سيكون يدويًا فقط.",
    saveWorkflow: "حفظ سير العمل",
    autoLayout: "تنسيق تلقائي",
    nodeProperties: "خصائص العقدة",
    labelName: "التسمية / الاسم",
    actionName: "اسم الإجراء",
    start: "البداية",
    end: "النهاية",
    approve: "موافقة",
    review: "مراجعة",
    decision: "قرار (نعم/لا)",
    other: "أخرى",
    unknown: "غير معروف",
    noTriggersAvailable: "لا توجد مشغلات متاحة",
    label: "تسمية",
    orSeparator: "- أو -",
    workflowAssignments: "سير العمل",
    addAssignment: "إضافة تعيين",
    editAssignment: "تعديل التعيين",
    newAssignment: "تعيين جديد",
    deleteAssignment: "حذف التعيين",
    confirmDeleteAssignment: "هل أنت متأكد من حذف هذا التعيين؟",
    assignmentCreated: "تم إنشاء التعيين بنجاح",
    assignmentUpdated: "تم تحديث التعيين بنجاح",
    assignmentDeleted: "تم حذف التعيين بنجاح",
    workflowRequired: "سير العمل مطلوب",
    applyToDocTypes: "تطبيق على أنواع المستندات",
    excludeUsers: "استثناء مستخدمين",
    selectUsersToExclude: "اختر مستخدمين لاستثنائهم",
    selectWorkflow: "اختر سير العمل",
    workflowSelectHelp: "سيتم تطبيق سير العمل هذا تلقائياً",
    docTypes: "أنواع المستندات",
    allDocTypes: "كل الأنواع",
    roles: "الأدوار",
    allRoles: "كل الأدوار",
    exceptions: "استثناءات",
    // general: "عام", // Duplicate
    workflow: "سير العمل",
    noAssignmentsFound: "لا توجد تعيينات سير عمل.",
    noAssignmentsDesc: "تسمح لك التعيينات بتشغيل سير العمل تلقائيًا عند تحميل المستندات إلى هذا الموقع.",
    assignment: "التعيين",
    assigneeUser: "المعين (مستخدم)",
    assigneeRoleLabel: "المعين (دور)",
    noWorkflows: "لا توجد سير عمل",
    noWorkflowsDesc: "قم بإنشاء سير عمل جديد للبدء في أتمتة عملياتك.",
    roleManager: "مدير",
    roleReviewer: "مراجع",
    roleCustom: "دور مخصص...",
    roleLegalDept: "الإدارة القانونية",
    enterCustomRole: "أدخل دور مخصص",

    // Workflow Validation Errors
    createWorkflow: "إنشاء سير عمل",
    addStepsError: "يجب إضافة خطوات لسير العمل",
    workflowNameRequired: "اسم سير العمل مطلوب",
    startNodeRequired: "يجب أن يحتوي سير العمل على نقطة بداية (Start Node)",
    endNodeRequired: "يجب أن يحتوي سير العمل على نقطة نهاية (End Node)",
    flowDisconnectedError: "بعض العقد غير متصلة أو لا يمكن الوصول إلى النهاية من البداية",
    addTriggerError: "يجب اختيار مشغل واحد على الأقل",
    noIntermediateStepsError: "يجب أن يحتوي سير العمل على خطوة واحدة على الأقل بين البداية والنهاية",
    startEdgeTriggerRequired: "مطلوب إضافة مشغل على الرابط من البداية",
    startEdgeNameRequired: "مطلوب اسم للرابط الخاص بالمشغل",



    // Resource Picker
    selectTriggersScope: "تحديد المشغلات والنطاق",
    workspacesFiles: "مساحات العمل",
    documentTypes: "أنواع المستندات",
    peopleUsers: "الأشخاص والمستخدمين",
    addSelected: "إضافة المحدد",
    empty: "(فارغ)",
    selectAll: "تحديد الكل",
    deselectAll: "إلغاء تحديد الكل",

    // Task Actions
    // reject: "رفض", // Duplicate
    'attachedDocument': 'المستند المرفق',
    'view': 'عرض',
    triggerDescription: "حدد الشروط التي تبدأ سير العمل هذا تلقائيًا (مثل تحميل ملف PDF).",
    // approve: "موافقة",
    'dueDate': 'تاريخ الاستحقاق',
    submitData: "إرسال البيانات",
    markAsReviewed: "تحديد كمراجعة",
    reviewNotes: "ملاحظات المراجعة...",
    addComment: "أضف تعليقاً (اختياري)...",
    taskInstructions: "يرجى مراجعة المستندات/المعلومات المرفقة.",
    fillRequiredFields: "يرجى تعبئة الحقول المطلوبة",
    requiredFieldsPlaceholder: "مثال: تاريخ الانتهاء، المبلغ",
    // تمت إزالة التكرار: نعم، لا، عودة، خروج
    // ===== Obligations =====
    obligationsAndDeadlines: "الالتزامات والمواعيد النهائية",
    newObligation: "التزام جديد",
    editObligation: "تعديل الالتزام",
    searchObligationsPlaceholder: "بحث في الالتزامات...",
    noObligations: "لا توجد التزامات.",
    due: "مستحق",
    upcoming7days: "قادمة (7 أيام)",
    obligationTitlePlaceholder: "العنوان",
    obligationDescriptionPlaceholder: "الوصف",

    // ===== Retention Policies =====
    retentionSubtitle: "إدارة الاحتفاظ بالمستندات والأرشفة والسياسات القانونية",
    newPolicy: "سياسة جديدة",
    editPolicy: "تعديل السياسة",
    retentionWarning: "هام:",
    retentionWarningText: "تطبق سياسات الاحتفاظ تلقائيًا. لا يمكن حذف أو تعديل المستندات الخاضعة للحجز القانوني.",
    retentionPeriod: "فترة الاحتفاظ",
    actionAfterRetention: "الإجراء بعد الاحتفاظ",
    archive: "أرشفة",
    notify: "إشعار فقط",
    legalHoldPrevent: "حجز قانوني (منع الحذف)",
    policyName: "اسم السياسة",
    enterPolicyName: "أدخل اسم السياسة",
    unit: "وحدة",
    days: "أيام",
    months: "شهور",
    years: "سنين",

    // ===== Audit Logs =====
    auditLogsTitle: "سجلات التدقيق",
    auditLogsSubtitle: "تتبع نشاط النظام وأحداث الأمان",
    auditLogsSearch: "بحث",
    auditLogsSearchPlaceholder: "مستخدم، إجراء، كيان...",
    auditLogsAction: "الإجراء",
    auditLogsAllActions: "كل الإجراءات",
    auditLogsFrom: "من",
    auditLogsTo: "إلى",
    auditLogsEmpty: "لا توجد سجلات تدقيق تطابق معاييرك.",
    auditLogsTimestamp: "الختم الزمني",
    auditLogsUser: "المستخدم",
    auditLogsEntityType: "نوع الكيان",
    auditLogsEntityName: "اسم الكيان",

    // ===== Tenant Settings =====
    tenantSettings: "إدارة المستأجر",
    tenantSettingsSubtitle: "إدارة الإعدادات والسياسات والأمان على مستوى المستأجر",
    saveSettings: "حفظ الإعدادات",
    securitySettings: "إعدادات الأمان",
    enableExternalSharing: "تمكين المشاركة الخارجية",
    externalSharingDesc: "السماح للمستخدمين بمشاركة المستندات مع أطراف خارجية",
    enableDownloads: "تمكين تنزيل المستندات",
    downloadDesc: "السماح للمستخدمين بتنزيل المستندات محليًا",
    requireMFA: "طلب المصادقة الثنائية",
    mfaDesc: "إجبار جميع المستخدمين على تفعيل المصادقة الثنائية لتعزيز الأمان",
    sessionTimeout: "مهلة الجلسة (دقائق)",
    sessionTimeoutDesc: "تسجيل خروج المستخدمين تلقائيًا بعد هذه الفترة من عدم النشاط",
    agentSettings: "إعدادات الوكيل",
    enableAutoMode: "تمكين الوضع التلقائي",
    tenantAutoModeDesc: "السماح للوكلاء بتنفيذ الإجراءات تلقائيًا ضمن حدود الأمان",
    allowNonUserMessages: "السماح بمراسلة غير المستخدمين",
    nonUserMessagesDesc: "تمكين الوكلاء من إرسال تذكيرات لجهات اتصال خارجية",
    requireApproval: "طلب الموافقة لإجراءات الوكيل",
    approvalDesc: "يجب مراجعة إجراءات الوكيل قبل التنفيذ",
    agentRateLimit: "حد معدل الوكيل (إجراء/يوم)",
    rateLimitDesc: "الحد الأقصى لعدد إجراءات الوكيل في اليوم",
    analyzerSettings: "إعدادات محلل الخزنة",
    autoAnalyze: "تحليل تلقائي للمستندات عند الرفع",
    autoAnalyzeDesc: "تصنيف واستخراج البيانات تلقائيًا عند رفع المستندات",
    monthlyCredits: "رصيد المحلل الشهري",
    creditsDesc: "عدد الصفحات التي يمكن تحليلها شهريًا",
    confidenceThreshold: "عتبة الثقة",
    thresholdDesc: "المستندات التي تقل عن هذه الثقة تتطلب مراجعة يدوية",
    notificationSettings: "إعدادات الإشعارات",
    enableEmailNotifications: "تمكين إشعارات البريد الإلكتروني",
    enableWhatsAppNotifications: "تمكين إشعارات واتساب",
    dataSettings: "إعدادات البيانات والامتثال",
    dataRetention: "الاحتفاظ الافتراضي بالبيانات (أيام)",
    retentionDesc: "فترة الاحتفاظ الافتراضية للمستندات (يمكن تجاوزها لكل مساحة عمل)",
    enableAuditLogs: "تمكين سجلات التدقيق",
    auditLogsDesc: "تتبع جميع إجراءات المستخدم للامتثال والأمان",
    tenantInfo: "معلومات المستأجر",
    tenantName: "اسم المؤسسة",
    enterTenantName: "أدخل اسم المؤسسة",
    billingEmail: "بريد الفواتير",
    enterBillingEmail: "أدخل بريد الفواتير",

    // ===== Extractions =====
    extractionReviewTitle: "مراجعة الاستخراج",
    extractionPendingBadge: "انتظار",
    extractionEmpty: "لا توجد استخراجات معلقة للمراجعة",
    extractionDocumentId: "معرف المستند",
    extractionConfidence: "الثقة",
    extractionType: "النوع",
    extractionStatus: "الحالة",
    extractionFields: "الحقول المستخرجة",
    reviewBtn: "مراجعة",
    extractionQuickApprove: "اعتماد سريع",
    extractionReject: "رفض",
    extractionSubtitle: "مراجعة واعتماد البيانات المستخرجة بالذكاء الاصطناعي",

    // ===== Search & Invitations & Agent Actions =====
    keywordSearch: "بحث بالكلمات المفتاحية",
    semanticSearch: "بحث دلالي",
    askQuestionPlaceholder: "اطرح سؤالاً...",
    searchDocumentsPlaceholder: "ابحث في المستندات...",
    answer: "الإجابة",
    sources: "المصادر",
    results: "النتائج",
    match: "تطابق",
    source: "المصدر",
    noResultsFound: "لم يتم العثور على نتائج لـ",
    invitationsTitle: "طلبات مشاركة المستندات",
    invitationsSubtitle: "تتبع حالة طلبات المشاركة الخارجية ومسار الموافقة",
    invitationspending: "معلقة في مسار العمل",
    invitationsAll: "جميع الطلبات",
    invitationsEmpty: "لم يتم العثور على طلبات مشاركة.",
    invitationsWorkspace: "مساحة العمل",
    invitationsExpires: "تنتهي في",
    invitationsAccept: "قبول",
    invitationsDecline: "رفض",
    awaitingWorkflowApproval: "في انتظار الموافقة من شاشة المهام",
    goToTasks: "اذهب إلى المهام",
    sharedBy: "أرسلها",
    agentActionsDesc: "مراقبة واعتماد أنشطة الوكيل الآلي",
    agentActionsPending: "معلقة",
    agentActionsAll: "الكل",
    agentActionsEmpty: "لا توجد إجراءات وكيل",
    agentActionsReview: "مراجعة",
    agentActionsAction: "إجراء",
    agentActionsDescription: "الوصف",
    agentActionsStatus: "الحالة",
    agentActionsClose: "إغلاق",

    // ===== Tasks =====
    tasksTitle: 'المهمات',
    manageTasks: 'إدارة المهمات والمتابعة',
    newTask: 'مهمة جديدة',
    editTask: 'تعديل المهمة',
    searchTasksPlaceholder: 'البحث في المهمات...',
    lowPriority: 'منخفضة',
    mediumPriority: 'متوسطة',
    highPriority: 'عالية',
    taskPendingStatus: 'قيد الانتظار',
    taskInProgressStatus: 'قيد التنفيذ',
    taskCompletedStatus: 'مكتملة',
    taskRejectedStatus: 'مرفوضة',
    taskApprovedStatus: 'معتمدة',
    taskTerminatedStatus: 'منهية',
    priority: 'الأولوية',
    taskUpdatedSuccessfully: 'تم تحديث المهمة بنجاح',
    taskCreatedSuccessfully: 'تم إنشاء المهمة بنجاح',
    failedToUpdateTask: 'فشل تحديث المهمة',
    failedToCreateTask: 'فشل إنشاء المهمة',
    taskDeletedSuccessfully: 'تم حذف المهمة بنجاح',
    confirmDeleteTask: 'حذف المهمة',
    confirmDeleteTaskDescription: 'هل أنت متأكد من حذف هذه المهمة؟ لا يمكن التراجع عن هذا الإجراء.',
    noTasksFound: 'لم يتم العثور على مهمات',
    noTasksDescription: 'لا توجد مهمات حالياً في النظام.',

    // ===== Activities =====
    activitiesTitle: 'الأنشطة',
    activitiesSubtitle: 'متابعة سجل العمليات وتطور مسارات العمل في النظام',
    newActivity: 'نشاط جديد',
    searchActivitiesPlaceholder: 'البحث في الأنشطة...',
    noActivities: 'لم يتم العثور على أنشطة.',
    systemActivitiesWillShowHere: 'ستظهر هنا أنشطة النظام وسجلات مسارات العمل تلقائياً.',
    editActivity: 'تعديل النشاط',
    activityTitle: 'عنوان النشاط',
    activityTitlePlaceholder: 'العنوان',
    activityDescription: 'وصف النشاط',
    activityDescriptionPlaceholder: 'الوصف',
    inprogressStatus: 'قيد التنفيذ',
    inProgressStatus: 'قيد التنفيذ',
    confirmDeleteActivity: 'هل أنت متأكد من حذف هذا النشاط؟',
    taskNotFoundOrNotAssigned: 'المهمة غير موجودة أو غير مسندة لك.',
    failedToLoadTasks: 'فشل في تحميل المهام',
    failedToDeleteTask: 'فشل في حذف المهمة',
    enterTaskTitle: 'أدخل عنوان المهمة',
    enterTaskDescription: 'أدخل تفاصيل المهمة',

    // ===== Users =====
    users: 'المستخدمين',
    manageUsers: 'إدارة المستخدمين',
    createUser: 'إنشاء مستخدم',
    editUser: 'تعديل مستخدم',
    userCreatedSuccessfully: 'تم إنشاء المستخدم بنجاح',
    userUpdatedSuccessfully: 'تم تحديث المستخدم بنجاح',
    failedToCreateUser: 'فشل إنشاء المستخدم',
    failedToUpdateUser: 'فشل تحديث المستخدم',
    failedToLoadUsers: 'فشل تحميل المستخدمين',
    failedToLoadUser: 'فشل تحميل بيانات المستخدم',
    nameAr: 'الاسم (عربي)',
    roleRequired: 'يجب اختيار دور واحد على الأقل',
    nameEn: 'الاسم (إنجليزي)',
    identityNumber: 'رقم الهوية',
    mobileNumber: 'رقم الجوال',
    mobileCountryCode: 'رمز الدولة',
    isMain: 'مستخدم رئيسي',
    isActive: 'نشط',
    isAbsherDefaultOtp: 'رمز OTP الافتراضي لأبشر',
    isTwoFactorAuthentication: 'المصادقة الثنائية',
    authorizationLetter: 'خطاب التفويض',
    // roles: 'الأدوار', // Duplicate
    searchPlaceholder: 'بحث...',
    noUsersDescription: 'لا يوجد مستخدمون متاحون في النظام حالياً.',
    create: 'إنشاء',
    agentActionsReject: "رفض",
    agentActionsApprove: "اعتماد",
    loadingPreview: 'جاري تحميل المعاينة...',
    rolesAndPermissions: 'الأدوار والصلاحيات',
    teamFolderRolesAndPermissions: 'أدوار وصلاحيات مجلد الفريق',
    everything: 'كل شيء',
    canDo: 'يمكنه فعله',
    plus: '+',
    modules: 'الوحدات',
    accessRemoved: 'تم إزالة الوصول بنجاح',
    removeAccessError: 'فشل إزالة الوصول',
    confirmRemoveAccess: 'هل أنت متأكد من إزالة الوصول لهذا الشخص؟',
    paginationShowing: 'عرض',
    paginationTo: 'إلى',
    paginationOf: 'من',
    firstPage: 'الصفحة الأولى',
    previousPage: 'الصفحة السابقة',
    nextPage: 'الصفحة التالية',
    lastPage: 'الصفحة الأخيرة',
    selectRoles: 'اختر الأدوار',
    searchRoles: 'ابحث عن الأدوار...',
    expires: 'تنتهي في',
    documentAccess: 'الوصول للمستند',
    externalSharing: 'المشاركة الخارجية',
    permissionUpdated: 'تم تحديث الأذونات',
    documents: 'مستندات',
    user: 'مستخدم',
    editor: 'محرر',
    viewer: 'مشاهد',
    noDocumentsFoundDescription: 'حاول تعديل البحث أو التصفيات للعثور على ما تبحث عنه.',
    addDocumentAccess: 'إضافة وصول للمستند',
    selectUser: 'اختر مستخدم',
    permissionLevel: 'مستوى الصلاحية',
    grantAccess: 'منح الوصول',

    // Workflow Assignment Messages
    docTypeRequired: 'يجب اختيار نوع وثيقة واحد على الأقل',
    workflowAlreadyAssigned: 'تم تعيين سير العمل هذا بالفعل. يرجى تعديل التعيين الحالي.',
    wf_addNew: 'إضافة جديد',
    wf_createNewDocType: 'إنشاء نوع وثيقة جديد',
    wf_fillAllFields: 'يرجى ملء جميع الحقول',
    wf_docTypeCreated: 'تم إنشاء نوع الوثيقة بنجاح',
    wf_errorCreating: 'حدث خطأ أثناء الإنشاء',
    wf_allAssigned: 'تم تعيين جميع مسارات العمل المتاحة',
    wf_noMore: 'لا توجد مسارات عمل إضافية لتعيينها لهذا الموقع.',
    wf_triggers: 'المحفزات',
    workflowActiveMessage: 'مشاركة هذا المستند ستقوم بتفعيل سير العمل:',
    note: 'ملاحظة',
    workflowTriggered: 'تم تفعيل سير العمل',

    // ===== Raw Errors (Axios) =====
    'Network Error': 'خطأ في الشبكة',
    'Request failed with status code 500': 'خطأ في الخادم (500)',
    'Request failed with status code 404': 'غير موجود (404)',
    'timeout of 0ms exceeded': 'انتهاء مهلة الطلب',

    // ===== Generic Errors =====
    networkError: 'خطأ في الشبكة',
    serverError: 'خطأ في الخادم',
    connectionRefused: 'تم رفض الاتصال',
    unauthorized: 'غير مصرح',
    forbidden: 'ممنوع',
    notFound: 'غير موجود',
    unknownError: 'حدث خطأ غير متوقع',
    requestTimeout: 'انتهت مهلة الطلب',
    serviceUnavailable: 'الخدمة غير متاحة',
    processTask: 'معالجة',
    companyInfo: 'بيانات الشركة',
    personalData: 'البيانات الشخصية',
    // View modes
    tableView: 'عرض الجدول',
    // Dashboard
    browseWorkspaces: 'تصفح مساحات العمل',
    openWorkspaceToUpload: 'افتح مساحة عمل لرفع المستندات',
    manageYourWorkflow: 'إدارة سير العمل الخاص بك',
    trackAndExecute: 'تتبع مهامك المعلقة ونفذ سير العمل بسهولة.',
    viewTasks: 'عرض المهام',
    manageWorkflows: 'إدارة سير العمل',
    // Invitations table
    // Workflows
    updatedAt: 'تاريخ التحديث',
    // Activities
    systemActivity: 'نشاط النظام',
    // Shared table headers
    action: 'الإجراء',
    myCompanies: 'شركاتي',
    'My Companies': 'شركاتي',
    manageMyCompanies: 'إدارة شركاتك',
    addNewCompany: 'إضافة شركة جديدة',
    companyCreatedSuccessfully: 'تمت إضافة الشركة بنجاح',
    companyType: 'نوع الشركة',
    noCompaniesFound: 'لا توجد شركات',
    noCompaniesDescription: 'لا توجد شركات مضافة لك حالياً.',
    failedToLoadCompanies: 'فشل في تحميل الشركات',
    failedToCreateCompany: 'فشل إضافة الشركة',
  },
  en: {
    // Sidebar
    'allDocuments': 'All Documents',
    'newDocument': 'New Document',
    'documentsLabel': 'DOCUMENTS',
    'foldersLabel': 'Workspace',
    'workspaces': 'Workspaces',
    'addWorkspace': 'Add Workspace',
    'workspaceName': 'Workspace Name',
    'workspaceType': 'Workspace Type',
    'enterWorkspaceName': 'Enter workspace name',
    'workspaceNameRequired': 'Workspace name is required',
    'errorCreatingWorkspace': 'Failed to create workspace',
    'errorUpdatingWorkspace': 'Failed to update workspace',
    'workspaceUpdated': 'Workspace updated successfully',
    'workspaceUpdatePendingWorkflow': 'Workflow Initiated. Workspace update pending approval.',
    'editWorkspace': 'Edit Workspace',
    'save': 'Save',
    'saving': 'Saving...',
    'workspaceSlug': 'URL Slug',
    'workspaceSlugPlaceholder': 'e.g: my-workspace',
    'workspaceSlugHelp': 'Only lowercase letters and dashes allowed',
    'workspaceSlugRequired': 'Slug is required',
    'workspacePrivacy': 'Privacy',
    'workspaceStorage': 'Storage Limit (MB)',
    'allowInvitesLabel': 'Allow inviting new members',
    'private': 'Private',
    'internal': 'Internal',
    'public': 'Public',
    'tenantIdNotFound': 'Could not find tenant ID. Please log in again.',
    'board': 'Board',
    'legal': 'Legal',
    'compliance': 'Compliance',
    'hr': 'HR',
    'projects': 'Projects',
    'add': 'Add',
    'allFiles': 'All Files',
    'boardMeetings': 'Board Meetings',
    'generalAssembly': 'General Assembly Meetings',
    'committees': 'Committee Meetings',
    'resolutions': 'Resolutions',
    'quickAccess': 'QUICK ACCESS',
    'file': 'File',
    'folder': 'Folder',
    'folders': 'Folders',
    'select': 'Select',
    'totalDocuments': 'Total Documents',
    'totalWorkspaces': 'Total Workspaces',
    'unsentDocuments': 'Unsent Documents',
    'subject': 'Subject',
    'updated': 'Updated',
    'progress': 'Progress',
    'signingWorkflow': 'SIGNING WORKFLOW',
    'noRecipientsYet': 'No recipients added yet',
    'viewDocument': 'View Document',
    'filters': 'Filters',
    'searchDocuments': 'Search documents...',
    'editFields': 'Edit Fields',
    'documentPreview': 'Document Preview',
    'openInNewTab': 'Open in new tab',
    'errorSaving': 'Error saving',
    'current': 'Current',
    'pendingTasks': 'Pending Tasks',
    'upcomingObligations': 'Upcoming Obligations',
    'pendingAgentActions': 'Pending Agent Actions',
    'recentActivity': 'Recent Activity',
    'dashboard': 'Dashboard',
    'welcomeBack': 'Welcome back ,',
    'dashboardGreetingDesc': "Here's what's happening with your documents today.",
    'dashboardSubtitle': 'Your vault overview and insights',
    'aiSearchPlaceholder': "Ask AI: 'Show pending documents' or 'Find contracts from last week'...",
    'latestUpdates': 'Latest updates on your documents',
    'documentCreated': 'Document created',
    'getStartedTasks': 'Get started with common tasks',
    'uploadAndSend': 'Upload and send for signature',
    'useTemplate': 'Use Template',
    'startFromTemplate': 'Start from a template',
    'teamSettings': 'Team Settings',
    'manageTeamMembers': 'Manage team members',
    'readyToSend': 'Ready to send?',
    'createAndSign': 'Create a new document and get it signed in minutes.',
    'daysAgo': 'days ago',
    'viewAll': 'View All',
    'seeMore': 'See more',
    'seeLess': 'See less',
    'noRecentActivity': 'No recent activity found.',
    'quickActions': 'Quick Actions',
    'createTask': 'Create Task',
    'startWorkflow': 'Start Workflow',
    'noUpcomingObligations': 'No upcoming obligations',
    'items': 'items',
    'viewDetails': 'View Details',
    'noPendingActions': 'No pending actions',
    'needsApproval': 'needs approval',
    'reviewActions': 'Review Actions',
    'addFolder': 'Add Folder',
    'folderName': 'Folder Name',
    'enterFolderName': 'Enter folder name',
    'folderNameRequired': 'Folder name is required',
    'isStarred': 'Starred',
    'removeFromStarred': 'Remove from starred',
    'addToStarred': 'Add to starred',
    'addToFavorites': 'Add to favorites',
    'removeFromFavorites': 'Remove from favorites',
    'addedToFavorites': 'Added to favorites',
    'removedFromFavorites': 'Removed from favorites',
    'errorUpdatingFavorites': 'Error updating favorites',
    'noStarredItems': 'No starred items yet',
    'noItemsFound': 'No items found',
    'noDocumentsFound': 'No documents found',
    'sharedWithMe': 'Shared with me',
    'searchVault': 'Search Vault',
    'tasks': 'Tasks',
    'activities': 'Activities',
    'obligations': 'Obligations',
    'workflowInstances': 'Workflow Instances',
    'retentionPolicies': 'Retention Policies',
    'extractionReview': 'Extraction Review',
    'invitations': 'Invitations',
    'agentActions': 'Agent Actions',
    'auditLogs': 'Audit Logs',
    'adminSettings': 'Admin Settings',
    'noWorkspacesYet': 'No workspaces yet',
    'noWorkspacesDesc': 'Create your first workspace to start organizing your documents.',
    'newWorkspace': 'New Workspace',
    'createWorkspaceDesc': 'Create a new workspace to organize your documents.',

    // Menu Actions
    'openMenu': 'Open menu',
    'moreActions': 'More Actions',
    'share': 'Share',
    'duplicate': 'Duplicate',
    'delete': 'Delete',
    'download': 'Download',
    'rename': 'Rename',
    'copy': 'Copy',
    'cut': 'Cut',
    'paste': 'Paste',
    'starred': 'Starred',

    // Accessibility
    'breadcrumb': 'Breadcrumb',
    'starredSubtitle': 'All files you have starred',
    'noStarredDocuments': 'No starred documents',
    'noStarredDocumentsDesc': 'Star important files to easily access them from here',
    'sharedSubtitle': 'Files shared with you by others',
    'noSharedDocuments': 'No shared files',
    'noSharedDocumentsDesc': 'Files shared with you will appear here',

    // Workspace Features
    'workspace': 'Workspace',
    'members': 'Members',
    'workspaceMembers': 'Workspace Members',
    'inviteMembers': 'Invite Members',
    'member': 'Member',
    'joinedDate': 'Joined Date',
    'removeMember': 'Remove Member',
    'confirmRemoveMember': 'Are you sure you want to remove this member?',
    'inviteToWorkspace': 'Invite to Workspace',
    'inviteDesc': 'Send an invitation to join this workspace.',
    'inviteMembersDescription': 'Invite users to collaborate in this workspace.',
    'emailAddress': 'Email Address',
    'admin': 'Admin',
    'guest': 'Guest',
    'optional': 'Optional',
    'sendInvite': 'Send Invite',
    'inviteSentSuccess': 'Invite sent successfully!',
    'settings': 'Settings',
    'workspaceSettings': 'Workspace Settings',
    'generalSettings': 'General Settings',
    'saveChanges': 'Save Changes',
    'dangerZone': 'Danger Zone',
    'confirmDeleteWorkspace': 'Are you sure you want to delete this workspace and all its contents?',
    'workspaceDeleted': 'Workspace deleted successfully.',
    'errorDeletingWorkspace': 'Failed to delete workspace',
    'deleteWorkspace': 'Delete Workspace',
    'deleteFolder': 'Delete Folder',
    'confirmDeleteFolder': 'Are you sure you want to delete this folder and all its contents?',
    'folderDeleted': 'Folder deleted successfully',
    'errorDeletingFolder': 'Failed to delete folder',
    'confirmDeleteDocument': 'Are you sure you want to delete this document?',
    'documentDeleted': 'Document deleted successfully',
    'errorDeletingDocument': 'Failed to delete document',
    'recycleBin': 'Recycle Bin',
    'errorLoadingWorkspace': 'Error loading workspace',
    'restore': 'Restore',
    'Msg_RestoredSuccessfully': 'Restored successfully',
    'resendSuccess': 'Workflow resent successfully',




    'actions': 'Actions',
    'type': 'Type',
    'deletedBy': 'Deleted By',
    'deletedAt': 'Deleted At',
    'document': 'Document',
    'sortBy': 'Sort by',
    'name': 'Name',
    'pendingActions': 'Pending Actions',
    documentsRequireAttention: 'documents require your attention',
    noDocumentsFoundDescription: 'Try adjusting your search or filters to find what you are looking for.',
    addDocumentAccess: 'Add Document Access',
    selectUser: 'Select User',
    permissionLevel: 'Permission Level',
    grantAccess: 'Grant Access',
    'suggested': 'Suggested',
    'recentDocuments': 'Recent Documents',
    'all': 'All',
    'pendingSignature': 'Pending Signature',
    'inReview': 'In Review',
    'approved': 'Approved',
    'signed': 'Signed',
    'searchInVault': 'Search in Vault',
    'advancedSearch': 'Advanced search',
    'askVault': 'Ask Vault',
    'goToGRC': 'Go to GRC',
    'menu': 'Menu',
    'changePassword': 'Change Password',
    'logout': 'Logout',
    'home': 'Home',
    'requiredField': 'Required field',
    'license': 'License',
    'partnershipAgreement': 'Partnership Agreement - Strategic',
    'agreement': 'Agreement',
    'annualReport': 'Annual Report 2024',
    'report': 'Report',
    'dataProcessing': 'Data Processing Agreement',
    'consultingContract': 'Consulting Contract - Q1 2025',
    'antiMoneyLaundering': 'Anti-Money Laundering Policy',
    'shareholderAgreement': 'Shareholder Agreement - Series A',

    // Status
    'expired': 'Expired',
    'draft': 'Draft',

    // Dates
    'today': 'Today',
    'yesterday': 'Yesterday',
    'dec26': 'Dec 26',
    'dec18': 'Dec 18',

    // Registration
    'createAccount': 'Create New Account',
    'signUpMessage': 'Sign up to access all features',
    'fullName': 'Full Name',
    'enterFullName': 'Enter your full name',
    'fullNameAr': 'Full Name (Arabic)',
    'enterFullNameAr': 'Enter full name in Arabic',
    'fullNameEn': 'Full Name (English)',
    'enterFullNameEn': 'Enter full name in English',
    'companyName': 'Company Name',
    'enterCompanyName': 'Enter company name',
    'companyNameAr': 'Company Name (Arabic)',
    'enterCompanyNameAr': 'Enter company name in Arabic',
    'companyNameEn': 'Company Name (English)',
    'enterCompanyNameEn': 'Enter company name in English',
    'email': 'Email',
    'enterEmail': 'Enter your email',
    'password': 'Password',
    'enterPassword': 'Enter your password',
    'confirmPassword': 'Confirm Password',
    'enterConfirmPassword': 'Re-enter your password',
    'register': 'Register',
    'registering': 'Registering...',
    'alreadyHaveAccount': 'Already have an account?',
    'login': 'Login',

    // Validation
    'nameRequired': 'Name is required',
    'nameMinLength': 'Name must be at least 2 characters',
    'fullNameArRequired': 'Full name in Arabic is required',
    'fullNameEnRequired': 'Full name in English is required',
    'companyNameArRequired': 'Company name in Arabic is required',
    'companyNameEnRequired': 'Company name in English is required',
    'emailRequired': 'Email is required',
    'emailInvalid': 'Invalid email address',
    'passwordRequired': 'Password is required',
    'passwordMinLength': 'Password must be at least 8 characters',
    'passwordLowercase': 'Password must contain a lowercase letter',
    'passwordUppercase': 'Password must contain an uppercase letter',
    'passwordNumber': 'Password must contain a number',
    'passwordSpecialChar': 'Password must contain a special character',
    'confirmPasswordRequired': 'Confirm password is required',
    'passwordsNotMatch': 'Passwords do not match',
    'weak': 'Weak',
    'medium': 'Medium',
    'strong': 'Strong',
    'registrationSuccess': 'Registration successful!',
    'registrationError': 'Registration error occurred',
    'title': 'Title',
    'enterTitle': 'Enter document title',
    'upload': 'Upload',
    'clickToUpload': 'Click to select a file',
    'uploading': 'Uploading...',
    'documentTitle': 'Document Title',
    'selectWorkspace': 'Select Workspace',
    'fillAllFields': 'Please fill in all fields',
    'errorLoadingWorkspaces': 'Failed to load workspaces',
    'selectDocumentType': 'Select Document Type',
    'uploadError': 'Failed to upload document. Please try again.',
    'updateDocument': 'Update Document',
    'updateError': 'Failed to update document. Please try again.',
    'update': 'Update',
    'updating': 'Updating...',
    'lowConfidence': 'Low Confidence',
    'mediumConfidence': 'Medium Confidence',
    'highConfidence': 'High Confidence',
    'reviewDocumentClassification': 'Review Document Classification',
    'reviewRequiredMessage': 'This classification requires your review and confirmation.',
    'highConfidenceMessage': 'The AI is confident about this classification, but please verify.',
    'confidence': 'Confidence',
    'extractedFields': 'Extracted Fields',
    'reviewFieldsMessage': 'Review and correct the extracted information below:',
    'enterValue': 'Enter value',
    'lowConfidenceWarning': 'Low Confidence',
    'lowConfidenceWarningMessage': 'The AI has low confidence in this classification. Please carefully review all fields before approving.',
    'reject': 'Reject',
    'approveAndSave': 'Approve & Save',
    'previewFailed': 'Preview failed',
    'confirmDelete': 'Are you sure you want to delete this document?',
    'deleteSuccess': 'Document deleted successfully',
    'deleteFailed': 'Failed to delete document',

    // Login
    'loginTitle': 'Sign In',
    'loginMessage': 'Sign in to access your account',
    'forgotPassword': 'Forgot Password?',
    'rememberMe': 'Remember me',
    'loginBtn': 'Sign In',
    'loggingIn': 'Signing In...',
    'noAccount': "Don't have an account?",
    'signUp': 'Create one',
    'passwordMinLoginLength': 'Password must be at least 6 characters',
    'loginSuccess': 'Login successful!',
    'companyChangedSuccess': 'Company changed successfully',
    'selectCompany': 'Select Company',
    'selectCompanySubtitle': 'Please choose one of your companies to continue',
    'searchCompanyPlaceholder': 'Search for a company...',
    'adminEmail': 'Admin Email',
    'adminPassword': 'Admin Password',
    'companyRequired': 'Company selection is required',
    'loginError': 'Login error occurred',
    'invalidCredentials': 'Invalid email or password',
    'partnerTab': 'Partner',
    'employeeTab': 'Employee',
    'adminPartnerLoginTitle': 'Admin Partner Login',
    'enterIdentityNumber': 'Enter Identity Number',
    'identityNumberRequired': 'Identity Number is required',
    'otpSentSuccess': 'The verification code has been sent successfully',
    'otpSentToPhones': 'The verification code has been sent to the following numbers:',
    'seconds': 'seconds',

    // Forgot Password
    'forgotPasswordTitle': 'Forgot Password?',
    'forgotPasswordMessage': 'Enter your email address and we will send you a link to reset your password.',
    'sendResetLink': 'Send Reset Link',
    'resetLinkSent': 'Password reset link sent to your email',
    'sending': 'Sending...',
    'verifyEmailTitle': 'Verify Your Email',
    'verifyEmailMessage': 'We sent a verification code to',
    'verificationCode': 'Verification Code',
    'enterVerificationCode': 'Enter 5-digit code',
    'verificationHint': 'Check your email for the code',
    'verify': 'Verify',
    'verifyingCode': 'Verifying Code...',
    'resendCode': 'Resend Code',
    'resendCodeSent': 'Code sent to your email!',
    'resendOtp': 'Resend OTP',
    'resendOtpIn': 'Resend OTP in',
    'resetPasswordTitle': 'Reset Password',
    'resetPasswordMessage': 'Enter your new password below',
    'newPassword': 'New Password',
    'resetPassword': 'Reset Password',
    'resettingPassword': 'Resetting Password...',
    'passwordResetSuccess': 'Password reset successfully!',
    'passwordResetError': 'Error resetting password',
    'passwordValidationError': 'Please check your password requirements',
    'invalidVerificationCode': 'Invalid verification code',
    'verificationCodeRequired': 'Please enter verification code',
    'error': 'An error occurred',
    'mustBeArabic': 'Must be in Arabic',
    'mustBeEnglish': 'Must be in English',

    // Invitation Accept
    'verifyInvitation': 'Verify Your Invitation',
    'otpSentTo': 'We\'ve sent a 6-digit verification code to',
    'enterOtpCode': 'Enter Code',
    'verifyCode': 'Verify Code',
    'verifyingOtp': 'Verifying...',
    'didntReceiveCode': 'Didn\'t receive the code?',
    'resendOtpCode': 'Resend Code',
    'invalidOtp': 'Invalid OTP. Please try again.',
    'enterAllDigits': 'Please enter all 6 digits',
    'invitationAccepted': 'Invitation accepted successfully!',
    'invalidInvitationLink': 'Invalid invitation link',
    'otpGenerationFailed': 'Failed to generate OTP',
    'goToLogin': 'Go to Login',
    'previewNotAvailable': 'Preview not available for this file type',
    'downloadToView': 'Download to View',
    'fileReady': 'Your document is ready for download',
    'backToLogin': 'Back to Login',

    // Profile
    'profile': 'Profile',
    'profileSubtitle': 'Manage your personal account information',
    'edit': 'Edit',
    // 'save': 'Save',

    'personalInfo': 'Personal Information',
    'firstName': 'First Name',
    'lastName': 'Last Name',
    'phone': 'Phone Number',
    'bio': 'Bio',
    'address': 'Address',
    'city': 'City',
    'country': 'Country',
    'workInfo': 'Work Information',
    'company': 'Company',
    'position': 'Position',
    'joinedOn': 'Joined on',
    'registeredUser': 'Registered User',
    'businessAccount': 'Business Account',
    'organizationInfo': 'Organization Info',
    'accountType': 'Account Type',

    // Change Password
    'currentPassword': 'Current Password',
    'enterCurrentPassword': 'Enter your current password',

    'enterNewPassword': 'Enter your new password',
    'confirmNewPassword': 'Confirm your new password',
    'updatePassword': 'Update Password',
    'changingPassword': 'Changing Password...',
    'changePasswordMessage': 'Update your password',
    'passwordChangeSuccess': 'Password changed successfully!',
    'passwordChangeError': 'Error changing password',
    'passwordSameAsOld': 'New password must be different from the old one',
    'passwordsMatch': 'Passwords match',
    'fixErrors': 'Please fix the errors in the form',
    'passwordStrength': 'Password strength',
    'backToHome': 'Back to Home',

    // AI Chat
    'aiChatGreeting': 'How can I help you today?',
    'whatToStartWith': 'What do you want to start with?',
    'message': 'Message',
    'uploadFile': 'Upload File',
    'draftMode': 'Draft Mode',
    'autoMode': 'Auto Mode',
    'agentUsingPrefix': "I'm using the",
    'agentModePrefix': 'in',
    'draftModeDesc': 'In Draft mode, I will propose actions for review and approval before execution.',
    'autoModeDesc': 'In Auto mode, I will execute actions automatically within defined safety rules.',
    'agentFileUploaded': 'I see you uploaded',
    'agentMessageReceived': 'I received your message: ',
    'agentSimulatedResponse': 'This is a simulated response.',
    'selectAgent': 'Select Agent',
    'removeAttachment': 'Remove attachment',

    // Agents
    'agent_auto': 'Smart Assistant (Auto)',
    'agent_docs': 'Documents Agent',
    'agent_deadlines': 'Deadlines & Expiry',
    'agent_signing': 'Signing Agent',
    'agent_governance': 'Governance Agent',
    'agent_audit': 'Audit & Compliance',
    'agent_access': 'Access & Permissions',
    'agent_insights': 'Insights & Summary',

    // Agent Descriptions
    'agent_desc_auto': 'Best for general queries',
    'agent_desc_docs': 'Query your files',
    'agent_desc_deadlines': 'Track timings',
    'agent_desc_signing': 'Signatures & flows',
    'agent_desc_governance': 'Compliance rules',
    'agent_desc_audit': 'Audit logs',
    'agent_desc_access': 'User roles',
    'agent_desc_insights': 'Analytics',

    // Suggestions
    'suggestion_expiring': 'Expiring Documents',
    'suggestion_expiring_desc': 'Find documents expiring this week',
    'suggestion_summarize': 'Summarize Meeting',
    'suggestion_summarize_desc': 'Summarize board meeting minutes',
    'suggestion_access': 'Access Check',
    'suggestion_access_desc': 'Who has access to HR folder?',
    'suggestion_draft': 'Draft Contract',
    'suggestion_draft_desc': 'Draft a non-disclosure agreement',

    // Common
    'gridView': 'Grid View',
    'listView': 'List View',
    'back': 'Back',
    'details': 'Details',
    'yes': 'Yes',
    'no': 'No',
    'documentNotFound': 'Document not found',

    // Document Fields
    'id': 'ID',
    'category': 'Category',
    'status': 'Status',
    'date': 'Date',
    'size': 'Size',
    'general': 'General',
    'documentFetchError': 'Failed to load document details',
    'kb': 'KB',
    'noDocuments': 'No Documents Found',
    'noDocumentsDescription': 'There are no documents in this workspace yet. Start by uploading one.',
    'noVersionsDescription': 'There are no previous versions of this document.',

    // Share Modal
    'shareDocument': 'Share Document',
    'shareDescription': 'Share this link with others to view',
    'copyLink': 'Copy Link',
    'linkCopied': 'Copied!',
    'close': 'Close',
    'expiryDateKeywords': 'Expiry date is required',
    'invalidEmail': 'Invalid email address',
    'confirmDeleteInvitation': 'Are you sure you want to remove access for this user?',
    'invitationDeleted': 'Access removed successfully',
    'deleteInvitationFailed': 'Failed to remove access',
    'fetchInvitationsFailed': 'Failed to fetch invitations',
    'shareSuccess': 'Document shared successfully',
    'shareFailed': 'Failed to share document',
    'peopleWithAccess': 'People with access',
    'sharing': 'Sharing...',
    'expiryDate': 'Expiry Date',

    // Document Upload
    'uploadDocument': 'Upload Document',
    'uploadNewDocument': 'Upload New Document',
    'dragDropFile': 'Drag and drop file here',
    'orClickToBrowse': 'or click to browse',
    'documentName': 'Document Name',
    'enterDocumentName': 'Enter document name',
    'selectCategory': 'Select Category',
    'financial': 'Financial',
    'technical': 'Technical',
    'description': 'Description',
    'enterDescription': 'Enter description',


    'workflows': 'Workflows',
    'noActiveWorkflows': 'No active workflows',
    'by': 'By',
    'assignedTo': 'Assigned To',
    'documentType': 'Document Type',
    'tags': 'Tags',
    'enterTags': 'e.g. urgent, confidential',
    'Draft': 'Draft',
    'InReview': 'In Review',
    'Approved': 'Approved',
    'Signed': 'Signed',
    'Pending': 'Pending',
    'Rejected': 'Rejected',
    'Executed': 'Executed',
    'active': 'Active',
    'inactive': 'Inactive',
    'created': 'Created',





    // ===== Workspace Invite & Permissions =====
    manageWorkspaceMembers: 'Manage Workspace Members',
    manageWorkspaceMembersDesc: 'You can change the role of each user from the list below:',
    adding: 'Adding...',
    role: 'Role',
    viewer: 'Viewer',
    editor: 'Editor',
    owner: 'Owner',
    managePermissions: 'Manage Permissions',
    inviteUser: 'Invite User',
    userAlreadyHasAccess: 'User already has access',
    confirmRemoveUser: 'Are you sure you want to remove access for this user?',
    searchUsers: 'Search users...',
    noUsersFound: 'No users found',
    invite: 'Invite',
    cancel: 'Cancel',
    you: 'You',
    failedToLoadMembers: 'Failed to load members',
    memberRemovedSuccessfully: 'Member removed successfully',
    failedToRemoveMember: 'Failed to remove member',
    roleUpdatedSuccessfully: 'Role updated successfully',
    failedToUpdateRole: 'Failed to update role',
    failedToLoadData: 'Failed to load data',
    invitationSentSuccessfully: 'Invitation sent successfully',
    failedToInviteUser: 'Failed to invite user',
    noMembersFound: 'No members found',
    noMembersFoundDescription: 'Invite users to collaborate on this workspace.',
    Admin: 'Admin',
    Editor: 'Editor',
    Viewer: 'Viewer',

    // ===== Document Details =====
    legalHold: 'Legal Hold',
    legalHoldActive: 'This workspace is under Legal Hold',
    legalHoldBannerTitle: '⚠️ Legal Hold Active',
    legalHoldBannerDesc: 'This workspace is under a Legal Hold — editing and deleting are locked until the hold is lifted.',
    legalHoldLockedEdit: 'Editing is locked due to Legal Hold',
    legalHoldLockedDelete: 'Deletion is locked due to Legal Hold',
    legalHoldLockedMsg: 'System folders cannot be edited, deleted, or assigned workflows.',
    workspaceDeletePendingWorkflow: 'Delete request sent — awaiting approval in Tasks',
    documentDeletePendingWorkflow: 'Document deletion request sent — awaiting workflow approval',
    statusAndCompliance: 'Status & Compliance',
    generalInfo: 'General Information',
    activeHold: 'Active Hold',
    createdDate: 'Created Date',
    noDescription: 'No description provided for this document.',
    versionHistory: 'Version History',
    permissions: 'Permissions',
    documentDetails: 'Document Details',
    downloadDocument: 'Download Document',
    noOneHasAccess: 'No one has access yet',
    noVersions: 'No previous versions',
    removeAccess: 'Remove Access',

    // ===== Document Versions =====
    uploadNewVersion: 'Upload New Version',
    latest: 'Latest',
    confirmDeleteVersion: 'Are you sure you want to delete this version?',
    versionDeleted: 'Version deleted successfully',
    deleteError: 'Failed to delete version',
    versionsLoadError: 'Failed to load document versions',
    versionUploaded: 'New version uploaded successfully',

    // ===== Common =====
    search: "Search",

    // ===== Workflows =====
    workflowsTitle: "Workflows",
    requestedBy: "Requested By",
    relatedItem: "Related Item",
    WorkflowInstance: "Workflow Instance",
    deactivateWorkflow: "Deactivate Workflow",
    deactivateToEdit: "Deactivate workflow to edit",
    cannotEditActiveWorkflow: "Cannot edit an active workflow — please deactivate it first",
    onlyOneStartNodeAllowed: "Only one Start node is allowed per workflow.",
    onlyOneEndNodeAllowed: "Only one End node is allowed per workflow.",
    failedToSaveWorkflow: "Failed to save workflow",
    confirmDeactivateWfWithInstances: "There are active instances associated with this workflow. Deactivating will terminate them all and deactivate assignments. Are you sure?",
    workflowSaved: "Workflow saved successfully",
    activateWorkflow: "Activate Workflow",
    confirmActivateWf: "Are you sure you want to activate this workflow?",
    activateAssignmentsWithWorkflow: "Activate associated assignments as well",
    viewAssignments: "Configure Workflow Assignments",
    viewActiveInstances: "View Active Instances",
    workflowActivated: "Workflow Activated successfully",
    workflowDeactivated: "Workflow Deactivated successfully",
    deactivate: "Deactivate",
    activate: "Activate",
    workflowInstancesSubtitle: "Track active and completed workflow executions",
    searchWorkflowsPlaceholder: "Search workflows...",
    editWorkflow: "Edit Workflow",
    newWorkflow: "New Workflow",
    workflowNamePlaceholder: "Workflow Name",
    workflowDescriptionPlaceholder: "Description",
    draftStatus: "Draft",
    activeStatus: "Active",
    archivedStatus: "Archived",
    steps: "Steps",
    assignedWorkspaces: "Assigned Workspaces",
    activeInstances: "Active Instances",
    completedInstances: "Completed Instances",
    assignedDocuments: "Assigned Documents",
    Running: "Running",
    Completed: "Completed",
    Docs: "Documents",
    Folders: "Folders",
    Workspaces: "Workspaces",
    triggers: "Triggers",
    addStep: "Add Step",
    addTrigger: "Add Trigger",
    addTriggerGroup: "Add Trigger Group",
    editTriggerGroup: "Edit Trigger Group",
    triggerType: "Trigger Type",
    triggerValue: "Value / ID",
    fileFormatTrigger: "File Format (Extension)",
    personTrigger: "Person (User ID)",
    workspaceTrigger: "Workspace (Workspace ID)",
    folderEventTrigger: "Folder/Tag",
    stepTitle: "Step Title",
    actionType: "Action Type",
    instructions: "Instructions",
    requiredFields: "Required Fields (comma separated)",
    waitForDeps: "Waits For (Dependencies)",
    done: "Done",
    approveAction: "Approve/Reject",
    fillAction: "Fill Data",
    reviewAction: "Review",
    runningStatus: "Running",
    failedStatus: "Failed",
    completedStatus: "Completed",
    pausedStatus: "Paused",
    terminatedStatus: "Terminated",
    suspendedStatus: "Suspended",
    pendingStatus: "Pending",
    createdBy: "Created By",
    contextData: "Context Details",
    currentStep: "Current Step",
    startedAt: "Started At",
    completedAt: "Completed At",
    confirmDeleteWorkflow: 'Delete Workflow',
    confirmDeleteWorkflowDescription: 'Are you sure you want to delete this workflow? This action cannot be undone.',
    workflowDeletedSuccessfully: 'Workflow deleted successfully',
    failedToDeleteWorkflow: 'Failed to delete workflow',
    failedToLoadWorkflows: 'Failed to load workflows',
    failedToLoadWorkflow: 'Failed to load workflow info',
    processTask: 'Process Task',
    // View modes
    tableView: 'Table View',
    // Dashboard
    browseWorkspaces: 'Browse Workspaces',
    openWorkspaceToUpload: 'Open a workspace to upload documents',
    manageYourWorkflow: 'Manage Your Workflow',
    trackAndExecute: 'Track your pending tasks and execute workflows with ease.',
    viewTasks: 'View Tasks',
    manageWorkflows: 'Manage Workflows',
    // Invitations table
    sharedBy: 'Shared By',
    invitationsExpires: 'Expires',
    // Workflows
    updatedAt: 'Updated',
    // Activities
    activitiesTitle: 'Activities',
    activitiesSubtitle: 'Logs of all system activities and workflows',
    noActivities: 'No Activities',
    systemActivitiesWillShowHere: 'System activities and workflow logs will appear here.',
    systemActivity: 'System Activity',
    // Shared table headers
    action: 'Action',
    user: 'User',
    myCompanies: 'My Companies',
    'My Companies': 'My Companies',
    manageMyCompanies: 'Manage your companies',
    addNewCompany: 'Add New Company',
    companyCreatedSuccessfully: 'Company created successfully',
    companyType: 'Company Type',
    noCompaniesFound: 'No Companies Found',
    noCompaniesDescription: 'There are no companies assigned to you.',
    failedToLoadCompanies: 'Failed to load companies',
    failedToCreateCompany: 'Failed to create company',

    // Workflow Editor
    workflowSettings: "Workflow Settings",
    event: "Event",
    selectEvent: "Select Event",
    edgeProperties: "Connection Properties",
    deleteConnection: "Delete Connection",
    connectionName: "Connection Name",
    before: "Before",
    during: "During",
    after: "After",
    transitionForms: "Transition Forms",
    configureForms: "Configure Forms",
    scopeTriggers: "Triggers",
    selectTrigger: "Select Trigger",
    flowShapes: "Flow Shapes",
    instructionsTitle: "INSTRUCTIONS",
    dragShapesInstruction: "Drag shapes to the canvas. Connect them to define the flow. Select a node to configure properties on the right.",
    noScopesDefined: "No scopes defined. Usage will be manual only.",
    saveWorkflow: "Save Workflow",
    autoLayout: "Auto Layout",
    nodeProperties: "Node Properties",
    labelName: "Label / Name",
    actionName: "Action Name",
    start: "Start",
    end: "End",
    // approve: "Approve", // Duplicate
    // reject: "Reject", // Duplicate
    // review: "Review", // Duplicate
    decision: "Decision (Yes/No)",
    other: "Other",
    unknown: "Unknown",
    noTriggersAvailable: "No triggers available",
    label: "Label",
    orSeparator: "- OR -",
    workflowAssignments: "Workflow",
    addAssignment: "Add Assignment",
    editAssignment: "Edit Assignment",
    newAssignment: "New Assignment",
    deleteAssignment: "Delete Assignment",
    confirmDeleteAssignment: "Are you sure you want to delete this assignment?",
    assignmentCreated: "Assignment created successfully",
    assignmentUpdated: "Assignment updated successfully",
    assignmentDeleted: "Assignment deleted successfully",
    workflowRequired: "Workflow is required",
    applyToDocTypes: "Apply to Document Types",
    excludeUsers: "Exclude Users",
    selectUsersToExclude: "Select users to exclude",
    selectWorkflow: "Select Workflow",
    workflowSelectHelp: "This workflow will be applied automatically",
    docTypes: "Doc Types",
    allDocTypes: "All Types",
    roles: "Roles",
    allRoles: "All Roles",
    exceptions: "Exceptions",
    // general: "General", // Duplicate
    workflow: "Workflow",
    noAssignmentsFound: "No workflow assignments found.",
    noAssignmentsDesc: "Assignments allow you to automatically trigger workflows when documents are uploaded to this location.",
    assignment: "Assignment",
    assigneeUser: "Assignee (User)",
    assigneeRoleLabel: "Assignee Role",
    noWorkflows: "No workflows",
    noWorkflowsDesc: "Create a new workflow to start automating your processes.",
    roleManager: "Manager",
    roleReviewer: "Reviewer",
    roleCustom: "Custom Role...",
    roleLegalDept: "Legal Department",
    enterCustomRole: "Enter Custom Role",
    fieldsConfigured: "fields configured",

    // Workflow Validation Errors
    createWorkflow: "Create Workflow",
    addStepsError: "You must add steps to the workflow",
    workflowNameRequired: "Workflow name is required",
    startNodeRequired: "Workflow must have a Start Node",
    endNodeRequired: "Workflow must have an End Node",
    flowDisconnectedError: "Some nodes are disconnected or the End node is unreachable from Start",
    addTriggerError: "At least one trigger is required",
    noIntermediateStepsError: "Workflow must have at least one step between Start and End",
    startEdgeTriggerRequired: "A trigger is required on the connection from Start",
    startEdgeNameRequired: "A name is required for the trigger connection",


    // Resource Picker
    selectTriggersScope: "Select Triggers & Scope",
    workspacesFiles: "Workspaces",
    documentTypes: "Document Types",
    peopleUsers: "People & Users",
    addSelected: "Add Selected",
    empty: "(Empty)",
    selectAll: "Select All",
    deselectAll: "Deselect All",

    // Task Actions
    'attachedDocument': 'Attached Document',
    'view': 'View',
    // reject: "Reject", // Duplicate
    triggerDescription: "Define conditions that automatically start this workflow (e.g. Upload a PDF).",
    approve: "Approve",
    'dueDate': 'Due Date',
    submitData: "Submit Data",
    markAsReviewed: "Mark as Reviewed",
    reviewNotes: "Review notes...",
    addComment: "Add a comment (optional)...",
    taskInstructions: "Please review the attached documents/info.",
    fillRequiredFields: "Please fill required fields",
    requiredFieldsPlaceholder: "e.g. Expiry Date, Amount",
    // تمت إزالة التكرار: Yes, No, Back, Logout
    // ===== Obligations =====
    obligationsAndDeadlines: "Obligations & Deadlines",
    newObligation: "New Obligation",
    editObligation: "Edit Obligation",
    searchObligationsPlaceholder: "Search obligations...",
    noObligations: "No obligations found.",
    due: "Due",
    upcoming7days: "Upcoming (7 days)",
    obligationTitlePlaceholder: "Title",
    obligationDescriptionPlaceholder: "Description",

    // ===== Retention Policies =====
    retentionSubtitle: "Manage document retention, archival, and legal hold policies",
    newPolicy: "New Policy",
    editPolicy: "Edit Policy",
    retentionWarning: "Important:",
    retentionWarningText: "Retention policies apply automatically. Documents under legal hold cannot be deleted or modified.",
    retentionPeriod: "Retention Period",
    actionAfterRetention: "Action After Retention",
    archive: "Archive",
    notify: "Notify Only",
    legalHoldPrevent: "Legal Hold (Prevent Deletion)",
    policyName: "Policy Name",
    enterPolicyName: "Enter policy name",
    unit: "Unit",
    days: "Days",
    months: "Months",
    years: "Years",

    // ===== Audit Logs =====
    auditLogsTitle: "Audit Logs",
    auditLogsSubtitle: "Track system activity and security events",
    auditLogsSearch: "Search",
    auditLogsSearchPlaceholder: "User, Action, Entity...",
    auditLogsAction: "Action",
    auditLogsAllActions: "All Actions",
    auditLogsFrom: "From",
    auditLogsTo: "To",
    auditLogsEmpty: "No audit logs found matching your criteria.",
    auditLogsTimestamp: "Timestamp",
    auditLogsUser: "User",
    auditLogsEntityType: "Entity Type",
    auditLogsEntityName: "Entity Name",

    // ===== Tenant Settings =====
    tenantSettings: "Tenant Administration",
    tenantSettingsSubtitle: "Manage tenant-wide settings, security, and policies",
    saveSettings: "Save Settings",
    securitySettings: "Security Settings",
    enableExternalSharing: "Enable External Sharing",
    externalSharingDesc: "Allow users to share documents with external parties",
    enableDownloads: "Enable Document Downloads",
    downloadDesc: "Allow users to download documents locally",
    requireMFA: "Require Multi-Factor Authentication",
    mfaDesc: "Force all users to enable MFA for enhanced security",
    sessionTimeout: "Session Timeout (minutes)",
    sessionTimeoutDesc: "Automatically log out users after this period of inactivity",
    agentSettings: "Agent Settings",
    enableAutoMode: "Enable Auto Mode",
    tenantAutoModeDesc: "Allow agents to execute actions automatically within safety guardrails",
    allowNonUserMessages: "Allow Messaging Non-Users",
    nonUserMessagesDesc: "Enable agents to send reminders to external contacts",
    requireApproval: "Require Approval for Agent Actions",
    approvalDesc: "Agent actions must be reviewed before execution",
    agentRateLimit: "Agent Rate Limit (actions/day)",
    rateLimitDesc: "Maximum number of agent actions per day",
    analyzerSettings: "Vault Analyzer Settings",
    autoAnalyze: "Auto-Analyze Documents on Upload",
    autoAnalyzeDesc: "Automatically classify and extract data when documents are uploaded",
    monthlyCredits: "Monthly Analyzer Credits",
    creditsDesc: "Number of pages that can be analyzed per month",
    confidenceThreshold: "Confidence Threshold",
    thresholdDesc: "Documents below this confidence require manual review",
    notificationSettings: "Notification Settings",
    enableEmailNotifications: "Enable Email Notifications",
    enableWhatsAppNotifications: "Enable WhatsApp Notifications",
    dataSettings: "Data & Compliance Settings",
    dataRetention: "Default Data Retention (days)",
    retentionDesc: "Default retention period for documents (can be overridden per workspace)",
    enableAuditLogs: "Enable Audit Logs",
    auditLogsDesc: "Track all user actions for compliance and security",
    tenantInfo: "Tenant Information",
    tenantName: "Organization Name",
    enterTenantName: "Enter organization name",
    billingEmail: "Billing Email",
    enterBillingEmail: "Enter billing email",

    // ===== Extractions =====
    extractionReviewTitle: "Extraction Review Queue",
    extractionPendingBadge: "pending",
    extractionEmpty: "No pending extractions to review",
    extractionDocumentId: "Document ID",
    extractionConfidence: "Confidence",
    extractionType: "Type",
    extractionStatus: "Status",
    extractionFields: "Extracted Fields",
    reviewBtn: "Review",
    extractionQuickApprove: "Quick Approve",
    extractionReject: "Reject",
    extractionSubtitle: "Review and approve AI-extracted document metadata",

    // ===== Search & Invitations & Agent Actions =====
    keywordSearch: "Keyword Search",
    semanticSearch: "Semantic Search",
    askQuestionPlaceholder: "Ask a question...",
    searchDocumentsPlaceholder: "Search documents...",
    answer: "Answer",
    sources: "Sources",
    results: "Results",
    match: "Match",
    source: "Source",
    noResultsFound: "No results found for",
    invitationsTitle: "Document Share Requests",
    invitationsSubtitle: "Monitor external share requests and their workflow approval status",
    invitationspending: "Pending Workflow",
    invitationsAll: "All Requests",
    invitationsEmpty: "No share requests found.",
    invitationsWorkspace: "Workspace",
    invitationsAccept: "Accept",
    invitationsDecline: "Decline",
    awaitingWorkflowApproval: "Awaiting approval in Tasks",
    goToTasks: "Go to Tasks",
    agentActionsDesc: "Monitor and approve automated agent activities",
    agentActionsPending: "Pending",
    agentActionsAll: "All",
    agentActionsEmpty: "No agent actions",
    agentActionsReview: "Review",
    agentActionsAction: "Action",
    agentActionsDescription: "Description",
    agentActionsStatus: "Status",
    agentActionsClose: "Close",
    agentActionsReject: "Reject",
    agentActionsApprove: "Approve",
    loadingPreview: "Loading preview...",
    accessRemoved: "Access removed successfully",
    removeAccessError: "Failed to remove access",
    confirmRemoveAccess: "Are you sure you want to remove this person's access?",
    paginationShowing: "Showing",
    paginationTo: "to",
    paginationOf: "of",
    firstPage: "First Page",
    previousPage: "Previous Page",
    nextPage: "Next Page",
    lastPage: "Last Page",

    // ===== Tasks =====
    tasksTitle: 'Tasks',
    manageTasks: 'Manage tasks and follow-ups',
    newTask: 'New Task',
    editTask: 'Edit Task',
    searchTasksPlaceholder: 'Search tasks...',
    lowPriority: 'Low',
    mediumPriority: 'Medium',
    highPriority: 'High',
    taskPendingStatus: 'Pending',
    taskInProgressStatus: 'In Progress',
    taskCompletedStatus: 'Completed',
    taskRejectedStatus: 'Rejected',
    taskApprovedStatus: 'Approved',
    taskTerminatedStatus: 'Terminated',
    priority: 'Priority',
    taskUpdatedSuccessfully: 'Task updated successfully',
    taskCreatedSuccessfully: 'Task created successfully',
    failedToUpdateTask: 'Failed to update task',
    failedToCreateTask: 'Failed to create task',
    taskDeletedSuccessfully: 'Task deleted successfully',
    confirmDeleteTask: 'Delete Task',
    confirmDeleteTaskDescription: 'Are you sure you want to delete this task? This action cannot be undone.',
    noTasksFound: 'No tasks found',
    noTasksDescription: 'There are no tasks available in the system at the moment.',

    // ===== Activities =====
    newActivity: 'New Activity',
    searchActivitiesPlaceholder: 'Search activities...',
    editActivity: 'Edit Activity',
    activityTitle: 'Activity Title',
    activityTitlePlaceholder: 'Title',
    activityDescription: 'Activity Description',
    activityDescriptionPlaceholder: 'Description',
    inprogressStatus: 'In Progress',
    inProgressStatus: 'In Progress',
    confirmDeleteActivity: 'Are you sure you want to delete this activity?',
    taskNotFoundOrNotAssigned: 'Task not found or not assigned to you.',
    failedToLoadTasks: 'Failed to load tasks',
    failedToDeleteTask: 'Failed to delete task',
    enterTaskTitle: 'Enter task title',
    enterTaskDescription: 'Enter description',

    // ===== Users =====
    users: "Users",
    manageUsers: "Manage Users",
    createUser: "Create User",
    editUser: "Edit User",
    userCreatedSuccessfully: "User created successfully",
    userUpdatedSuccessfully: "User updated successfully",
    failedToCreateUser: "Failed to create user",
    failedToUpdateUser: "Failed to update user",
    failedToLoadUsers: "Failed to load users",
    failedToLoadUser: "Failed to load user info",
    nameAr: "Name (Arabic)",
    roleRequired: "At least one role is required",
    nameEn: "Name (English)",
    identityNumber: "Identity Number",
    mobileNumber: "Mobile Number",
    mobileCountryCode: "Country Code",
    isMain: "Main User",
    isActive: "Is Active",
    isAbsherDefaultOtp: "Absher Default OTP",
    isTwoFactorAuthentication: "Two-Factor Authentication",
    authorizationLetter: "Authorization Letter",
    // roles: "Roles", // Duplicate
    searchPlaceholder: "Search...",
    noUsersDescription: "No users available in the system at the moment.",
    create: "Create",
    selectRoles: "Select Roles",
    searchRoles: "Search Roles...",
    rolesAndPermissions: 'Roles & Permissions',
    teamFolderRolesAndPermissions: 'Team Folder roles and permissions',
    everything: 'Everything',
    canDo: 'can do',
    plus: '+',
    modules: 'Modules',
    expires: 'Expires',
    documentAccess: 'Document Access',
    externalSharing: 'External Sharing',
    permissionUpdated: 'Permission updated',
    documents: 'Documents',

    // Workflow Assignment
    docTypeRequired: 'At least one document type is required',
    workflowAlreadyAssigned: 'Workflow is already assigned. Please update the existing assignment.',
    wf_addNew: 'Add New',
    wf_createNewDocType: 'Create New Document Type',
    wf_fillAllFields: 'Please fill all fields',
    wf_docTypeCreated: 'Document Type Created Successfully',
    wf_errorCreating: 'Error creating document type',
    wf_allAssigned: 'All available workflows have been assigned',
    wf_noMore: 'There are no more workflows to assign to this location.',
    wf_triggers: 'Triggers',
    workflowActiveMessage: 'Sharing this document will trigger the workflow:',
    note: 'Note',
    workflowTriggered: 'Workflow Triggered',
    companyInfo: 'Company Info',
    personalData: 'Personal Data',
    // View modes
    // Dashboard
    // Invitations table
    // Workflows
  },

};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem("language") as Language) || "ar";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "ar" ? "en" : "ar"));
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  const value = useMemo(() => ({ language, toggleLanguage, t }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
